/** BIT 14 Sep 2026. Boundary: U.S. 11 Sep completed close; HK 14 Sep 10:57 HKT intraday only. */
import { ArrowRight, CalendarDays, CheckCircle2, CircleAlert, ExternalLink, Printer } from "lucide-react";
import { useState } from "react";
import usData from "../../../data/2026-09-14/us_market.json";
import hkData from "../../../data/2026-09-14/hk_market.json";
import thesisData from "../../../data/2026-09-14/thesis.json";
import sourcesData from "../../../data/2026-09-14/sources.json";
import detailData from "../../../data/2026-09-14/market_analytics_detail.json";

type Lang = "TW" | "CN" | "EN";
type Section = "overview" | "us" | "hk" | "cross" | "week" | "sources";
type Mode = "education" | "analysis";
const us: any = usData, hk: any = hkData, thesis: any = thesisData, detail: any = detailData, sources: any[] = (sourcesData as any).sources;
const base = import.meta.env.BASE_URL;
const pct = (n: number) => `${n > 0 ? "+" : ""}${n.toFixed(2)}%`;
const heat = (n: number) => n > 0.1 ? "#10B99A" : n < -0.1 ? "#FF6A1A" : "#E5E7EB";
const labels: Record<Lang, Record<string, string>> = { EN: {}, TW: { Technology:"科技", "Communication Services":"通訊服務", "Health Care":"醫療保健", Utilities:"公用事業", Financials:"金融", "Real Estate":"房地產", Materials:"原材料", "Consumer Discretionary":"非必需消費", Industrials:"工業", "Consumer Staples":"必需消費", Energy:"能源" }, CN: { Technology:"科技", "Communication Services":"通信服务", "Health Care":"医疗保健", Utilities:"公用事业", Financials:"金融", "Real Estate":"房地产", Materials:"原材料", "Consumer Discretionary":"非必需消费", Industrials:"工业", "Consumer Staples":"必需消费", Energy:"能源" } };

const text: Record<Lang, any> = {
  TW: {
    edition:"BIT MARKET INTELLIGENCE · DAILY · 2026.09.14", asof:"as-of：2026年9月14日10:57 HKT · 美股完成時段為9月11日；港股為10:57 HKT盤中快照",
    nav:{overview:"總覽",us:"美股",hk:"港股",cross:"跨市場",week:"本週關注",sources:"來源"}, modes:{education:"投教閱讀",analysis:"分析閱讀"}, print:"導出完整PDF", printAction:"列印／儲存PDF", fact:"事實", meaning:"市場含義", next:"下一驗證", positive:"正面確認", negative:"負面確認",
    title:"油價回落帶來反彈，但較高日度利率與狹窄中期廣度仍令估值敏感。",
    thesis:"9月11日美股在油價自早前週度急升中回落、投資者消化8月CPI後反彈；但美國國債日度平價收益率仍高，而11個板塊ETF代理的5日與20日正回報比例均僅18.2%。Oracle的雲端基建數據是已核實的AI需求證據；NVIDIA與Anthropic的投資洽談及AI研發節奏討論仍是帶歸因的未確認報道。下一步是聯儲局溝通、能源／航運的可歸因發展及港股完成資料。",
    summary:"可核實的是三大指數上升、VIX日度收市15.84、10年期日度平價收益率4.96%、CPI讀數、油價媒體報道結算及Oracle官方業績。這不是價格預測，而是必須由政策、能源與更廣市場參與共同檢驗的反彈論點。",
    usTitle:"美股：油價回落協助全面反彈，但多日板塊代理廣度仍然狹窄。", hkTitle:"港股：10:57 HKT官方受限快照偏穩；完成收市、成交及南向資料仍待核對。", crossTitle:"跨市場：能源風險、日度收益率、AI資本需求與政策日程必須分開驗證。", weekTitle:"本週關注：聯儲局、能源／航運、港股完成資料及AI披露均屬條件式驗證。",
    cards:[["美股／9月11日完成收市","Dow +0.98% · S&P +0.86% · Nasdaq +0.96%","媒體將反彈與油價回落及通脹讀數消化並列；不把任何單一因素寫成唯一因果。"],["港股／9月14日10:57 HKT","HSI +0.10% · HSCEI +0.06% · HSTECH +0.20%","恒生指數公司資料受系統故障及15分鐘更新限制；僅為盤中快照。"]],
    learn:["怎樣讀今天的報告","先分開9月11日完成美股收市、9月14日帶時間戳的港股快照和9月16日美國聯儲局日程；再檢查一日反彈是否與5日／20日廣度、收益率、油價及公司披露互相印證。",["日度平價收益率是官方每日參考，並非某一分鐘成交收益率。","81.8%的一日板塊代理正回報不等於中期趨勢轉向：5日與20日代理廣度均只有18.2%。","港股網站有延遲更新限制；盤中數字不能代替收市、成交額或南向資金。"]],
    analyse:["當前論點與失效條件","基本情景是油價回落提供短暫風險偏好修復，但較高日度利率與狹窄多日廣度限制了把單日反彈外推為全面趨勢。AI基建需求應以官方業績和後續披露檢驗，不能以談判報道代替。",["可歸因的降溫配合較低油價、較低利率壓力及更廣完成市場參與，會支持反彈論點。","能源風險再升溫並配合長端壓力或廣度回落，會削弱單日修復論點。","若公司披露不支持需求、產能、融資與治理共同改善，AI敘事應維持選擇性而非整體化。"]],
    macro:[["VIX","15.84","Cboe 9月11日日度收市。"],["2Y／10Y／30Y","4.63%／4.96%／5.35%","美國財政部9月11日日度平價收益率；非盤中成交報價。"],["板塊代理廣度","81.8% 1D／18.2% 5D／18.2% 20D","11個Select Sector SPDR ETF代理；不是交易所A/D廣度。"],["能源結算","WTI $100.05／Brent $104.61","9月11日完成時段媒體報道；不據此推導持久油價路徑。"]],
    company:[["ORCL","FY27 Q1官方披露","收入$193.45億、雲端收入$116.07億、IaaS收入$74億及RPO $6,640億；自由現金流為負$50億。","同時提供AI基建需求與資本投入／現金轉換張力的證據，不能延伸為所有硬件或軟件公司的結果。","後續正式披露是否支持需求、可用產能、融資及利潤率共同執行。"],["NVDA／Anthropic","Reuters報道的洽談","Reuters報道Anthropic與NVIDIA洽談可能IPO錨定投資，消息人士稱NVIDIA或考慮最多$100億；談判可改變，兩家公司未向Reuters確認。","這是融資與算力生態的條件式線索，不是已完成投資、鎖定訂單或估值結論。","公司正式公告、招股文件或其他可歸因披露。"],["OpenAI／Anthropic","研發節奏報道","Reuters引述Bloomberg報道稱Altman曾向員工表示OpenAI可與其他實驗室協調研發節奏；Anthropic發言人稱有意就工具發布速度與業界合作。","不能把它寫成三家公司已達成放緩前沿模型研發的協議，亦不能推導單一股價方向。","可核實的公司政策、監管文件及資本開支／產品時間表披露。"]],
    hk:[["前一完成收市","未獨立取得","本輪證據未取得可審計的上一完成港股收市、成交或南向資金數字，不以推算替代。"],["今日盤中快照","10:57 HKT · HSI +0.10%","恒生指數公司官方讀數；系統故障下只提供有限15分鐘更新，並非收市。"],["科技／生科相對位置","HSTECH +0.20% · HSBIO +3.40%","官方盤中指數位置；不歸因於單一政策、資金流或公司消息。"],["收市後核對","待官方資料","核對完成指數、HKEX成交、指數服務狀態及Historical Daily Stock Connect；不估算南向。"]],
    cross:["油價回落與較高週度風險溢價","官方日度收益率／估值邊界","Oracle官方基建需求與資本支出張力","聯儲局、香港收市與公司正式披露"], crossBody:"可觀察的是9月11日油價在此前週度上升後回落、股市反彈與日度收益率仍高同時出現。Saudi East-West管道的預防性關閉及區域事件均須按來源歸因；不確認航道已恢復正常、任何停火／協議結果或單一持久價格路徑。", scenarios:[["正面","具來源的降溫消息配合較低原油、較低長端壓力及更廣完成市場參與；官方港股完成資料沒有惡化。"],["基準","油價／地緣與收益率仍具敏感性，單日股票修復與狹窄多日廣度並存；AI證據保持公司特定。"],["負面","可核實升級伴隨較高油價、長端壓力或更弱廣度；聯儲局／公司披露進一步收緊估值或資金假設。"]], sourceNote:"本報告分開完成價格、官方日度CPI／收益率／VIX、帶時間戳的香港盤中數據、官方日程、公司正式披露及帶歸因的媒體報道。已確定的FOMC結果、三家公司AI協議、OpenAI IPO延後、航運恢復、精確加密／外匯／金屬數字及未核實個股說法均沒有升格為結論。"
  },
  CN: {
    edition:"BIT MARKET INTELLIGENCE · DAILY · 2026.09.14", asof:"as-of：2026年9月14日10:57 HKT · 美股完成时段为9月11日；港股为10:57 HKT盘中快照", nav:{overview:"总览",us:"美股",hk:"港股",cross:"跨市场",week:"本周关注",sources:"来源"}, modes:{education:"投教阅读",analysis:"分析阅读"}, print:"导出完整PDF", printAction:"打印／保存PDF", fact:"事实", meaning:"市场含义", next:"下一验证", positive:"正面确认", negative:"负面确认",
    title:"油价回落带来反弹，但较高日度利率与狭窄中期广度仍使估值敏感。", thesis:"9月11日美股在油价从此前周度急升中回落、投资者消化8月CPI后反弹；但美国国债日度平价收益率仍高，而11个板块ETF代理的5日与20日正回报比例均仅18.2%。Oracle的云基础设施数据是已核实的AI需求证据；NVIDIA与Anthropic的投资洽谈及AI研发节奏讨论仍是带归因的未确认报道。下一步是美联储沟通、能源／航运的可归因发展及港股完成数据。", summary:"可核实的是三大指数上涨、VIX日度收市15.84、10年期日度平价收益率4.96%、CPI读数、油价媒体报道结算及Oracle官方业绩。这不是价格预测，而是必须由政策、能源与更广市场参与共同检验的反弹论点。", usTitle:"美股：油价回落帮助全面反弹，但多日板块代理广度仍然狭窄。", hkTitle:"港股：10:57 HKT官方受限快照偏稳；完成收市、成交与南向数据仍待核对。", crossTitle:"跨市场：能源风险、日度收益率、AI资本需求与政策日程必须分开验证。", weekTitle:"本周关注：美联储、能源／航运、港股完成数据及AI披露均属条件式验证。",
    cards:[["美股／9月11日完成收市","Dow +0.98% · S&P +0.86% · Nasdaq +0.96%","媒体将反弹与油价回落及通胀读数消化并列；不把任何单一因素写成唯一因果。"],["港股／9月14日10:57 HKT","HSI +0.10% · HSCEI +0.06% · HSTECH +0.20%","恒生指数公司资料受系统故障及15分钟更新限制；仅为盘中快照。"]], learn:["怎样读今天的报告","先分开9月11日完成美股收市、9月14日带时间戳的港股快照和9月16日美国美联储日程；再检查一日反弹是否与5日／20日广度、收益率、油价及公司披露相互印证。",["日度平价收益率是官方每日参考，并非某一分钟成交收益率。","81.8%的一日板块代理正回报不等于中期趋势转向：5日与20日代理广度均只有18.2%。","港股网站有延迟更新限制；盘中数字不能代替收市、成交额或南向资金。"]], analyse:["当前论点与失效条件","基准情景是油价回落提供短暂风险偏好修复，但较高日度利率与狭窄多日广度限制了把单日反弹外推为全面趋势。AI基建需求应以官方业绩和后续披露检验，不能以谈判报道代替。",["可归因的降温配合较低油价、较低利率压力及更广完成市场参与，会支持反弹论点。","能源风险再升温并配合长端压力或广度回落，会削弱单日修复论点。","若公司披露不支持需求、产能、融资与治理共同改善，AI叙事应保持选择性而非整体化。"]],
    macro:[["VIX","15.84","Cboe 9月11日日度收市。"],["2Y／10Y／30Y","4.63%／4.96%／5.35%","美国财政部9月11日日度平价收益率；非盘中成交报价。"],["板块代理广度","81.8% 1D／18.2% 5D／18.2% 20D","11个Select Sector SPDR ETF代理；不是交易所A/D广度。"],["能源结算","WTI $100.05／Brent $104.61","9月11日完成时段媒体报道；不据此推导持久油价路径。"]],
    company:[["ORCL","FY27 Q1官方披露","收入$193.45亿、云收入$116.07亿、IaaS收入$74亿及RPO $6,640亿；自由现金流为负$50亿。","这同时提供AI基础设施需求与资本投入／现金转换张力的证据，不能延伸为所有硬件或软件公司的结果。","后续正式披露是否支持需求、可用产能、融资及利润率共同执行。"],["NVDA／Anthropic","Reuters报道的洽谈","Reuters报道Anthropic与NVIDIA洽谈可能IPO锚定投资，消息人士称NVIDIA或考虑最多$100亿；谈判可改变，两家公司未向Reuters确认。","这是融资与算力生态的条件式线索，不是已完成投资、锁定订单或估值结论。","公司正式公告、招股文件或其他可归因披露。"],["OpenAI／Anthropic","研发节奏报道","Reuters引述Bloomberg报道称Altman曾向员工表示OpenAI可与其他实验室协调研发节奏；Anthropic发言人称有意就工具发布速度与业界合作。","不能把它写成三家公司已达成放缓前沿模型研发的协议，也不能推导单一股价方向。","可核实的公司政策、监管文件及资本开支／产品时间表披露。"]],
    hk:[["前一完成收市","未独立取得","本轮证据未取得可审计的上一完成港股收市、成交或南向资金数字，不以推算替代。"],["今日盘中快照","10:57 HKT · HSI +0.10%","恒生指数公司官方读数；系统故障下只提供有限15分钟更新，并非收市。"],["科技／生科相对位置","HSTECH +0.20% · HSBIO +3.40%","官方盘中指数位置；不归因于单一政策、资金流或公司消息。"],["收市后核对","待官方资料","核对完成指数、HKEX成交、指数服务状态及Historical Daily Stock Connect；不估算南向。"]],
    cross:["油价回落与较高周度风险溢价","官方日度收益率／估值边界","Oracle官方基础设施需求与资本开支张力","美联储、香港收市与公司正式披露"], crossBody:"可观察的是9月11日油价在此前周度上升后回落、股市反弹与日度收益率仍高同时出现。Saudi East-West管道的预防性关闭及区域事件均须按来源归因；不确认航道已恢复正常、任何停火／协议结果或单一持久价格路径。", scenarios:[["正面","具来源的降温消息配合较低原油、较低长端压力及更广完成市场参与；官方港股完成数据没有恶化。"],["基准","油价／地缘与收益率仍具敏感性，单日股票修复与狭窄多日广度并存；AI证据保持公司特定。"],["负面","可核实升级伴随较高油价、长端压力或更弱广度；美联储／公司披露进一步收紧估值或资金假设。"]], sourceNote:"本报告分开完成价格、官方日度CPI／收益率／VIX、带时间戳的香港盘中数据、官方日程、公司正式披露及带归因的媒体报道。已确定的FOMC结果、三家公司AI协议、OpenAI IPO延后、航运恢复、精确加密／外汇／金属数字及未核实个股说法均没有升级为结论。"
  },
  EN: {
    edition:"BIT MARKET INTELLIGENCE · DAILY · 2026.09.14", asof:"As of 14 Sep 2026 10:57 HKT · completed U.S. session: 11 Sep; Hong Kong: 10:57 HKT intraday snapshot", nav:{overview:"Overview",us:"U.S. Market",hk:"Hong Kong",cross:"Cross-market",week:"This Week",sources:"Sources"}, modes:{education:"Education reading",analysis:"Analysis reading"}, print:"Export full PDF", printAction:"Print / Save PDF", fact:"Fact", meaning:"What it means", next:"Next validation", positive:"Positive confirmation", negative:"Negative confirmation",
    title:"Oil’s pullback supported a rebound, but high daily yields and narrow medium-term breadth keep valuations sensitive.", thesis:"The 11 September U.S. session rebounded as oil retreated from an earlier weekly surge and investors absorbed August CPI, but Treasury daily par yields remained elevated while just 18.2% of the 11 sector-ETF proxies were positive over both five and twenty days. Oracle’s cloud-infrastructure metrics are verified AI-demand evidence; NVIDIA–Anthropic talks and AI-development-pace discussions remain attributable but unconfirmed reporting. The next tests are Fed communication, attributable energy/shipping developments and Hong Kong completed data.", summary:"Verified facts are higher broad indices, a 15.84 VIX daily close, a 4.96% 10Y Treasury daily par yield, August CPI readings, media-reported oil settlements and Oracle’s official results. This is not a price forecast: it is a rebound thesis that policy, energy and broader market participation must test together.", usTitle:"U.S.: Oil’s pullback supported a broad rebound, but multi-day sector-proxy breadth remains narrow.", hkTitle:"Hong Kong: the limited official 10:57 HKT snapshot is modestly positive; close, turnover and southbound data require verification.", crossTitle:"Cross-market: energy risk, daily yields, AI capital demand and policy timing must be verified separately.", weekTitle:"This week: Fed, energy/shipping, Hong Kong completed data and AI disclosures are conditional tests.",
    cards:[["U.S. / 11 Sep completed close","Dow +0.98% · S&P +0.86% · Nasdaq +0.96%","Coverage placed the rebound alongside oil’s pullback and CPI absorption; no one factor is claimed as the sole cause."],["Hong Kong / 14 Sep 10:57 HKT","HSI +0.10% · HSCEI +0.06% · HSTECH +0.20%","Official Hang Seng Indexes data are outage-limited and update every 15 minutes; this is intraday only."]], learn:["How to read today’s report","Separate the 11 September completed U.S. close, the timestamped 14 September Hong Kong snapshot and the 16 September Federal Reserve timetable. Then ask whether a one-day rebound is corroborated by 5D/20D breadth, yields, oil and company disclosures.",["A daily par yield is an official daily reference, not a yield traded at one minute.","An 81.8% positive one-day sector-proxy reading does not establish a medium-term reversal: both 5D and 20D breadth are 18.2%.","The Hong Kong website has a delayed-update limitation; intraday values cannot substitute for close, turnover or southbound flow."]], analyse:["Current thesis and invalidation conditions","The base case is that lower oil offers a temporary risk-appetite repair, while high daily yields and narrow multi-day breadth limit any extrapolation from one rebound. AI-infrastructure demand must be tested through official results and later disclosures, not financing-talk reports.",["Attributable de-escalation alongside lower oil, lower rate pressure and wider completed-market participation would support the rebound thesis.","Renewed energy stress with long-end pressure or weaker breadth would weaken the one-day repair case.","Without disclosures supporting demand, capacity, funding and governance together, AI evidence remains selective rather than market-wide."]],
    macro:[["VIX","15.84","Cboe 11 September daily close."],["2Y / 10Y / 30Y","4.63% / 4.96% / 5.35%","U.S. Treasury 11 September daily par yields; not intraday traded quotes."],["Sector proxy breadth","81.8% 1D / 18.2% 5D / 18.2% 20D","11 Select Sector SPDR ETF proxies; not exchange advance-decline breadth."],["Energy settlements","WTI $100.05 / Brent $104.61","11 September completed-session coverage; no durable oil path is inferred."]],
    company:[["ORCL","FY27 Q1 official release","$19.345bn revenue, $11.607bn cloud revenue, $7.4bn IaaS revenue and $664bn RPO; free cash flow was negative $5bn.","This is evidence of AI-infrastructure demand and capital-intensity/cash-conversion tension; it does not determine outcomes for every hardware or software name.","Whether later disclosures support demand, available capacity, funding and margin execution together."],["NVDA / Anthropic","Reuters-reported talks","Reuters reported talks for Anthropic to bring NVIDIA in as an anchor investor for a possible IPO; a source said NVIDIA was considering up to $10bn. The talks could change and neither company confirmed to Reuters.","This is a conditional financing-and-compute-ecosystem lead, not a completed investment, locked order or valuation conclusion.","Company announcements, an offering filing or other attributable disclosure."],["OpenAI / Anthropic","Development-pace report","Reuters, citing Bloomberg reporting, said Altman told staff OpenAI could pace development alongside other labs; an Anthropic spokesperson said it was interested in industry work on release pace.","This is not a confirmed three-company agreement to slow frontier-model development and does not imply a single share-price direction.","Verifiable company policy, regulatory records and capex/product-timetable disclosures."]],
    hk:[["Prior completed close","Not independently obtained","This evidence set does not contain an auditable prior Hong Kong close, turnover or southbound-flow figure; no estimate is substituted."],["Today intraday snapshot","10:57 HKT · HSI +0.10%","Official Hang Seng Indexes reading; only limited 15-minute updates are available during a system outage, so this is not a close."],["Technology / biotech position","HSTECH +0.20% · HSBIO +3.40%","Official intraday index positions; no single-policy, flow or company causality is inferred."],["Post-close check","Official data pending","Verify completed indices, HKEX turnover, index-service status and Historical Daily Stock Connect; do not estimate southbound flow."]],
    cross:["Oil pullback against a higher weekly risk premium","Official daily yields / valuation boundary","Oracle’s official infrastructure demand and capital-spending tension","Fed, Hong Kong close and formal company disclosures"], crossBody:"Observable evidence is that 11 September oil pulled back after an earlier weekly rise, equities rebounded and daily yields stayed elevated. The precautionary Saudi East-West pipeline shutdown and regional incidents remain source-attributed; they do not verify normalized transit, a ceasefire/agreement outcome or one durable price path.", scenarios:[["Positive","Attributable de-escalation arrives with lower crude, less long-end pressure and wider completed-market participation; official Hong Kong close data do not deteriorate."],["Base","Oil/geopolitical and yield sensitivity persists while a one-day equity repair coexists with narrow multi-day breadth; AI evidence remains company-specific."],["Negative","Verifiable escalation coincides with higher crude, duration pressure or weaker breadth; Fed or company disclosures tighten valuation or funding assumptions."]], sourceNote:"This report separates completed prices, official daily CPI/yields/VIX, timestamped Hong Kong intraday data, official schedules, company releases and attributable media reporting. A determined FOMC outcome, a three-company AI agreement, OpenAI IPO delay, normalized shipping, precise crypto/FX/metal figures and unverified stock claims are not promoted to conclusions."
  }
};

export default function DailySep14Full({ printAll=false }: { printAll?: boolean }) {
  const q = new URLSearchParams(window.location.search); const [lang,setLang]=useState<Lang>(((["TW","CN","EN"] as string[]).includes(q.get("lang")||"")?q.get("lang"):"CN") as Lang); const [section,setSection]=useState<Section>(((["us","hk","cross","week","sources"] as string[]).includes(q.get("market")||"")?q.get("market"):"overview") as Section); const [mode,setMode]=useState<Mode>("analysis"); const [windowSize,setWindowSize]=useState<"oneDay"|"fiveDay"|"twentyDay">("oneDay"); const t=text[lang];
  const go=(next:Section,nextLang=lang)=>{const u=new URL(window.location.href);u.searchParams.set("date","2026-09-14");u.searchParams.set("market",next);u.searchParams.set("lang",nextLang);u.searchParams.delete("export");window.history.replaceState({},"",u);window.dispatchEvent(new Event("bit-location"));setSection(next);setLang(nextLang);window.scrollTo({top:0,behavior:"smooth"});}; const print=()=>{const u=new URL(window.location.href);u.searchParams.set("date","2026-09-14");u.searchParams.set("lang",lang);u.searchParams.set("export","pdf");u.searchParams.delete("market");window.open(u,"_blank","noopener,noreferrer");};
  const Hero=({k,title,body}:any)=><section className="mx-auto max-w-[1200px] px-5 py-12 sm:px-10 lg:px-[var(--layout-padding)]"><p className="section-kicker">{k}</p><h1 className="section-title mt-3 max-w-5xl">{title}</h1><p className="mt-5 max-w-4xl text-[16px] leading-8 text-[#59657A]">{body}</p></section>;
  const Box=({a,b,c,click}:any)=><article onClick={click} className={`rounded-[12px] border border-[#E4E6EA] bg-white p-6 ${click?"cursor-pointer transition hover:border-[#0040FF]":""}`}><p className="font-mono text-[10px] font-bold tracking-[.13em] text-[#0040FF]">{a}</p><p className="mt-5 font-mono text-xl font-semibold">{b}</p><p className="mt-4 text-sm leading-7 text-[#59657A]">{c}</p>{click&&<p className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-[#0040FF]">{t.next}<ArrowRight size={14}/></p>}</article>;
  const Evidence=({d}:any)=><article className="rounded-[12px] border border-[#E4E6EA] bg-white p-6"><p className="font-display text-2xl">{d[0]} · {d[1]}</p><p className="mt-5 text-sm leading-7"><b>{t.fact} · </b>{d[2]}</p><p className="mt-4 text-sm leading-7 text-[#59657A]"><b>{t.meaning} · </b>{d[3]}</p><p className="mt-4 border-l-2 border-[#0040FF] pl-4 text-sm leading-7"><b>{t.next} · </b>{d[4]}</p></article>;
  const Overview=()=><main className="mx-auto max-w-[1200px] px-5 py-10 sm:px-10 lg:px-[var(--layout-padding)]"><section className="border-b border-[#E4E6EA] pb-10"><p className="section-kicker">{lang==="EN"?"DAILY / COMPLETED U.S. CLOSE → TODAY":lang==="TW"?"每日／完成美股收市 → 今日":"每日／完成美股收市 → 今日"}</p><h1 className="section-title mt-3 max-w-5xl">{t.title}</h1><p className="mt-6 max-w-4xl text-[17px] leading-8 text-[#59657A]">{t.thesis}</p><div className="mt-8 border-l-2 border-[#0040FF] bg-[#F5F7FA] p-5"><p className="font-mono text-[10px] font-bold tracking-[.14em] text-[#0040FF]">{lang==="EN"?"RESEARCH SUMMARY":lang==="TW"?"研究摘要":"研究摘要"}</p><p className="mt-3 text-[15px] leading-7">{t.summary}</p></div></section><section className="grid gap-5 py-10 lg:grid-cols-2">{t.cards.map((d:any,i:number)=><Box key={d[0]} a={d[0]} b={d[1]} c={d[2]} click={!printAll?()=>go(i?"hk":"us"):undefined}/>)}</section><section className="rounded-[12px] bg-[#0A0D14] p-7 text-white"><p className="font-mono text-[10px] tracking-[.16em] text-[#478DFF]">{lang==="EN"?"READING MODE / THESIS TEST":lang==="TW"?"閱讀模式／論點驗證":"阅读模式／论点验证"}</p><p className="mt-4 text-[16px] leading-7 text-[#EDF1F7]">{t[mode==="education"?"learn":"analyse"][1]}</p>{!printAll&&<button onClick={()=>go("week")} className="bit-action mt-6 inline-flex items-center gap-2 border border-[#478DFF] px-4 py-2 text-xs font-bold"><CalendarDays size={14}/>{t.nav.week}<ArrowRight size={14}/></button>}</section><section className="mt-10 rounded-[12px] border border-[#E4E6EA] p-6"><div className="flex flex-wrap items-center justify-between gap-4"><h2 className="font-display text-2xl">{t[mode==="education"?"learn":"analyse"][0]}</h2>{!printAll&&<div className="inline-flex rounded-[8px] border border-[#E4E6EA] p-1">{(["education","analysis"] as Mode[]).map(x=><button key={x} onClick={()=>setMode(x)} className={`bit-action px-3 py-2 text-xs font-bold ${mode===x?"bg-[#0040FF] text-white":"text-[#59657A]"}`}>{t.modes[x]}</button>)}</div>}</div><ul className="mt-5 grid gap-3 md:grid-cols-3">{t[mode==="education"?"learn":"analyse"][2].map((x:string)=><li key={x} className="border-l-2 border-[#0040FF] pl-4 text-sm leading-7 text-[#59657A]">{x}</li>)}</ul></section></main>;
  const Heatmap=()=><section className="bg-[#0A0D14] px-5 py-12 text-white sm:px-10 lg:px-[var(--layout-padding)]"><div className="mx-auto max-w-[1200px]"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="font-mono text-[10px] tracking-[.16em] text-[#478DFF]">{lang==="EN"?"SECTOR HEATMAP / COMPLETED 11 SEP":lang==="TW"?"板塊熱力圖／9月11日完成時段":"板块热力图／9月11日完成时段"}</p><p className="mt-3 text-sm text-[#BFC7D6]">{lang==="EN"?"Compare audited sector-proxy position across completed U.S. session windows.":lang==="TW"?"比較不同完成美股時段窗口的經審計板塊代理位置。":"比较不同完成美股时段窗口的经审计板块代理位置。"}</p></div>{!printAll&&<div className="flex gap-2">{(["oneDay","fiveDay","twentyDay"] as const).map(x=><button key={x} onClick={()=>setWindowSize(x)} className={`bit-action border px-3 py-2 font-mono text-[10px] font-bold ${windowSize===x?"border-[#478DFF] bg-[#0040FF] text-white":"border-white/20 text-[#BFC7D6]"}`}>{x==="oneDay"?"1D":x==="fiveDay"?"5D":"20D"}</button>)}</div>}</div><div className="mt-6 grid gap-2 sm:grid-cols-3">{detail.sector_heatmap.map((d:any)=><div key={d.symbol} className="min-h-28 rounded-[8px] p-4 text-[#0A0D14]" style={{background:heat(d[windowSize])}}><p className="font-mono text-[10px] font-bold tracking-[.1em]">{d.symbol} · {labels[lang][d.label]||d.label}</p><p className="mt-4 font-mono text-2xl">{pct(d[windowSize])}</p></div>)}</div><p className="mt-5 text-xs text-[#B0B9C9]">{lang==="EN"?"Green positive, grey neutral, orange-red negative.":lang==="TW"?"綠色正向、灰色中性、橙紅負向。":"绿色正向、灰色中性、橙红负向。"}</p></div></section>;
  const US=()=><main className="pb-12"><Hero k={lang==="EN"?"U.S. MARKET / COMPLETED 11 SEP":lang==="TW"?"美股／9月11日完成時段":"美股／9月11日完成时段"} title={t.usTitle} body={t.thesis}/><section className="bg-[#F5F7FA] px-5 py-8 sm:px-10 lg:px-[var(--layout-padding)]"><div className="mx-auto max-w-[1200px] grid border-l border-t border-[#E4E6EA] md:grid-cols-3">{Object.entries(us.index_close).map(([n,d]:any)=><div key={n} className="-ml-px -mt-px border border-[#E4E6EA] bg-white p-6"><p className="font-mono text-[10px] text-[#59657A]">{n}</p><p className="mt-4 font-mono text-3xl">{d.value.toLocaleString()}</p><p className="mt-2 font-mono text-sm text-[#17733B]">{pct(d.change_pct)}</p></div>)}</div></section><section className="mx-auto max-w-[1200px] px-5 py-12 sm:px-10 lg:px-[var(--layout-padding)]"><p className="section-kicker">{lang==="EN"?"MACRO / MARKET DRIVERS":lang==="TW"?"宏觀／市場驅動":"宏观／市场驱动"}</p><div className="mt-6 grid border-l border-t border-[#E4E6EA] lg:grid-cols-4">{t.macro.map((d:any)=><Box key={d[0]} a={d[0]} b={d[1]} c={d[2]}/>)}</div></section><section className="mx-auto max-w-[1200px] px-5 py-12 sm:px-10 lg:px-[var(--layout-padding)]"><p className="section-kicker">{lang==="EN"?"STOCKS / INDUSTRY CHAIN":lang==="TW"?"個股／產業鏈":"个股／产业链"}</p><div className="mt-6 grid gap-5 lg:grid-cols-3">{t.company.map((d:any)=><Evidence key={d[0]} d={d}/>)}</div></section><Heatmap/></main>;
  const HK=()=><main className="pb-12"><Hero k={lang==="EN"?"HONG KONG / 14 SEP 10:57 HKT INTRADAY":lang==="TW"?"港股／9月14日10:57 HKT盤中":"港股／9月14日10:57 HKT盘中"} title={t.hkTitle} body={lang==="EN"?hk.intraday_snapshot.limitation:lang==="TW"?"僅為盤中快照；不是完成收市、成交、南向資金或單一驅動結論。":"仅为盘中快照；不是完成收市、成交、南向资金或单一驱动结论。"}/><section className="mx-auto max-w-[1200px] px-5 py-10 sm:px-10 lg:px-[var(--layout-padding)]"><div className="grid gap-5 lg:grid-cols-2">{t.hk.map((d:any)=><Box key={d[0]} a={d[0]} b={d[1]} c={d[2]}/>)}</div></section></main>;
  const Cross=()=><main className="pb-12"><Hero k={lang==="EN"?"CROSS-MARKET / CONDITIONAL READ-THROUGH":lang==="TW"?"跨市場／條件式傳導":"跨市场／条件式传导"} title={t.crossTitle} body={t.crossBody}/><section className="mx-auto max-w-[1200px] px-5 py-8 sm:px-10 lg:px-[var(--layout-padding)]"><div className="rounded-[12px] bg-[#0A0D14] p-7 text-white"><div className="grid border-l border-t border-white/15 md:grid-cols-4">{t.cross.map((x:string,i:number)=><div key={x} className="-ml-px -mt-px min-h-32 border border-white/15 p-5"><p className="font-mono text-[10px] text-[#478DFF]">0{i+1}</p><p className="mt-4 text-sm leading-6">{x}</p></div>)}</div></div></section><section className="bg-[#F5F7FA] px-5 py-10 sm:px-10 lg:px-[var(--layout-padding)]"><div className="mx-auto grid max-w-[1200px] gap-5 lg:grid-cols-3">{t.scenarios.map((d:any,i:number)=><Box key={d[0]} a={d[0]} b="" c={d[1]}/>)}</div></section></main>;
  const Week=()=><main className="pb-12"><Hero k={lang==="EN"?"THIS WEEK / VERIFICATION AGENDA":lang==="TW"?"本週／驗證日程":"本周／验证日程"} title={t.weekTitle} body={lang==="EN"?"Official schedules and future conditions remain separated from outcomes.":lang==="TW"?"官方日程與未來條件均與結果分開。":"官方日程与未来条件均与结果分开。"}/><section className="bg-[#F5F7FA] px-5 py-10 sm:px-10 lg:px-[var(--layout-padding)]"><div className="mx-auto max-w-[1200px] space-y-4">{thesis.this_week.map((d:any,i:number)=><article key={d.id} className="grid gap-5 rounded-[12px] border border-[#E4E6EA] bg-white p-6 lg:grid-cols-[.8fr_1.4fr_1fr_1fr]"><div><p className="font-mono text-[10px] text-[#0040FF]">0{i+1}</p><p className="mt-4 font-display text-2xl">{d.event}</p><p className="mt-3 flex items-center gap-2 font-mono text-xs text-[#59657A]"><CalendarDays size={14}/>{d.when}</p></div><p className="text-sm leading-7 text-[#59657A]">{d.boundary}</p><p className="border-l-2 border-[#10B99A] pl-4 text-sm leading-6 text-[#17733B]"><CheckCircle2 className="mr-2 inline" size={15}/><b>{t.positive} · </b>{d.positive}</p><p className="border-l-2 border-[#F9584A] pl-4 text-sm leading-6 text-[#C22F26]"><CircleAlert className="mr-2 inline" size={15}/><b>{t.negative} · </b>{d.negative}</p></article>)}</div></section></main>;
  const Sources=()=><main className="mx-auto max-w-[1200px] px-5 py-10 sm:px-10 lg:px-[var(--layout-padding)]"><p className="section-kicker">{lang==="EN"?"SOURCES / AUDIT TRAIL":lang==="TW"?"來源／審計軌跡":"来源／审计轨迹"}</p><h1 className="section-title mt-3">{lang==="EN"?"Sources, entitlement and uncertainty boundary":lang==="TW"?"來源、權限與不確定性邊界":"来源、权限与不确定性边界"}</h1><p className="mt-5 max-w-4xl text-[16px] leading-7 text-[#59657A]">{t.sourceNote}</p><div className="mt-8 space-y-3">{sources.map(d=>printAll?<div key={d.id} className="rounded-[12px] border border-[#E4E6EA] p-5"><p className="font-mono text-[10px] text-[#0040FF]">[{d.id}] {d.market} · {d.tier}</p><p className="mt-2 text-sm">{d.label[lang]}</p></div>:<a key={d.id} href={d.url} target="_blank" rel="noreferrer" className="group flex items-center justify-between gap-4 rounded-[12px] border border-[#E4E6EA] p-5 hover:border-[#0040FF]"><div><p className="font-mono text-[10px] text-[#0040FF]">[{d.id}] {d.market} · {d.tier}</p><p className="mt-2 text-sm">{d.label[lang]}</p></div><ExternalLink size={17}/></a>)}</div><p className="mt-10 border-t border-[#E4E6EA] pt-6 text-xs leading-6 text-[#59657A]">{lang==="EN"?"AI-assisted content, based on the sources shown, for BIT internal market monitoring and research discussion. It is not investment advice, a securities recommendation, a buy/sell/short instruction or a guarantee of return.":lang==="TW"?"本內容由人工智能輔助整理，按所示來源供BIT內部市場監測與研究討論使用；不構成投資建議、證券推薦、買賣或沽空指令，亦不保證投資回報。":"本内容由人工智能辅助整理，按所示来源供BIT内部市场监测与研究讨论使用；不构成投资建议、证券推荐、买卖或沽空指令，也不保证投资回报。"}</p></main>;
  const Body=({s}:any)=>s==="overview"?<Overview/>:s==="us"?<US/>:s==="hk"?<HK/>:s==="cross"?<Cross/>:s==="week"?<Week/>:<Sources/>; const all=(<>{(["overview","us","hk","cross","week","sources"] as Section[]).map(s=><section key={s} className="bit-print-section"><div className="mx-auto max-w-[1200px] px-5 pt-10 sm:px-10"><p className="section-kicker">{t.nav[s]}</p></div><Body s={s}/></section>)}</>);
  if(printAll)return <div className="bit-v3 bit-print-document min-h-screen bg-white text-[#0A0D14]"><div className="mx-auto max-w-[1200px] px-5 py-8 sm:px-10"><p className="font-mono text-[10px] font-bold tracking-[.16em] text-[#0040FF]">{t.edition}</p><p className="mt-3 text-sm text-[#59657A]">{t.asof}</p><button onClick={()=>window.print()} className="bit-action bit-print-action mt-6 inline-flex items-center gap-2 border border-[#0040FF] px-4 py-2 text-xs font-bold text-[#0040FF]"><Printer size={15}/>{t.printAction}</button></div>{all}</div>;
  return <div className="bit-v3 min-h-screen bg-white text-[#0A0D14]"><header className="bit-reference-header sticky top-0 z-30 bg-white"><div className="bit-header-main mx-auto flex max-w-[1400px] flex-wrap items-center justify-between gap-3 px-5 py-4 sm:px-10 lg:px-[var(--layout-padding)]"><div className="flex min-w-0 items-center gap-3 sm:gap-8"><div className="flex shrink-0 items-center gap-2"><img src={`${base}brand/BIT-Logo-blue.svg`} alt="" className="h-8 w-8 rounded-[8px]"/><img src={`${base}brand/BIT-Logo-black.svg`} alt="BIT" className="bit-wordmark-crop"/></div><p className="min-w-0 font-mono text-[9px] font-bold tracking-[.13em] text-[#59657A]">{t.edition}</p></div><div className="flex items-center gap-2"><div className="inline-flex rounded-[8px] border border-[#E4E6EA] p-1">{(["TW","CN","EN"] as Lang[]).map(x=><button key={x} onClick={()=>go(section,x)} className={`bit-action px-2 py-1.5 font-mono text-[10px] font-bold ${lang===x?"bg-[#0040FF] text-white":"text-[#59657A]"}`}>{x}</button>)}</div><button onClick={print} className="bit-action inline-flex items-center gap-2 border border-[#0040FF] px-3 py-2 text-[10px] font-bold text-[#0040FF]"><Printer size={14}/>{t.print}</button></div></div><nav className="mx-auto flex max-w-[1400px] gap-1 overflow-x-auto border-t border-[#E4E6EA] px-5 py-2 sm:px-10 lg:px-[var(--layout-padding)]">{(Object.keys(t.nav) as Section[]).map(s=><button key={s} onClick={()=>go(s)} className={`bit-action shrink-0 px-3 py-2 text-xs font-bold ${section===s?"border-b-2 border-[#0040FF] text-[#0040FF]":"text-[#59657A]"}`}>{t.nav[s]}</button>)}</nav></header><Body s={section}/></div>;
}
