/**
 * BIT Market Intelligence — 1 Sep 2026 daily edition.
 * Evidence boundary: 31 Aug U.S. completed session; 1 Sep 10:09 HKT Hong Kong intraday only.
 * Design reminder: BIT white/black/blue shell; stocks and industry chain always precede the dark heatmap.
 */
import { ArrowRight, CalendarDays, CheckCircle2, CircleAlert, ExternalLink, Printer } from "lucide-react";
import { useState } from "react";
import usData from "../../../data/2026-09-01/us_market.json";
import hkData from "../../../data/2026-09-01/hk_market.json";
import thesisData from "../../../data/2026-09-01/thesis.json";
import sourceData from "../../../data/2026-09-01/sources.json";
import detailData from "../../../data/2026-09-01/market_analytics_detail.json";

type Lang = "TW" | "CN" | "EN";
type Section = "overview" | "us" | "hk" | "cross" | "week" | "sources";
type Mode = "education" | "analysis";
const us: any = usData;
const hk: any = hkData;
const thesis: any = thesisData;
const detail: any = detailData;
const sources: any[] = (sourceData as any).sources;
const base = import.meta.env.BASE_URL;
const pct = (value: number) => `${value > 0 ? "+" : ""}${value.toFixed(2)}%`;
const heat = (value: number) => value > 0.1 ? "#10B99A" : value < -0.1 ? "#FF6A1A" : "#E5E7EB";

const sectorLabels: Record<Lang, Record<string, string>> = {
  EN: {},
  TW: { Technology: "科技", "Communication Services": "通訊服務", "Health Care": "醫療保健", Utilities: "公用事業", Financials: "金融", "Real Estate": "房地產", Materials: "原材料", "Consumer Discretionary": "非必需消費", Industrials: "工業", "Consumer Staples": "必需消費", Energy: "能源" },
  CN: { Technology: "科技", "Communication Services": "通信服务", "Health Care": "医疗保健", Utilities: "公用事业", Financials: "金融", "Real Estate": "房地产", Materials: "原材料", "Consumer Discretionary": "非必需消费", Industrials: "工业", "Consumer Staples": "必需消费", Energy: "能源" }
};

const copy: Record<Lang, any> = {
  TW: {
    edition: "BIT MARKET INTELLIGENCE · DAILY · 2026.09.01",
    asof: "as-of：2026年9月1日10:09 HKT · 美股完成時段為8月31日；港股為10:09 HKT盤中快照",
    nav: { overview: "總覽", us: "美股", hk: "港股", cross: "跨市場", week: "本週關注", sources: "來源" },
    modes: { education: "投教閱讀", analysis: "分析閱讀" }, print: "導出完整PDF", printAction: "列印／儲存PDF", completed: "完成交易時段", intraday: "盤中快照", fact: "事實", meaning: "市場含義", next: "下一驗證", positive: "正面確認", negative: "負面確認", sourceTitle: "來源、權限與不確定性邊界",
    title: "能源風險溢價與較高日度收益率壓抑大市；AI僅呈現選擇性相對強勢。",
    thesis: "8月31日美股在油價上升、地緣消息與較高美國國債日度平價收益率背景下小幅收低；Energy是11個板塊ETF代理中唯一日升板塊。NVIDIA相對上升屬選擇性AI參與，不足以抵銷僅18.2%的一日板塊代理廣度。下一步要分開核對油價／地緣、港股完成收市與9月4日就業數據。",
    summary: "研究摘要", summaryText: "可核實的是三大指數收低、VIX日度收市14.92、Brent結算於$90.49、10年期日度平價收益率4.75%，以及NVIDIA相對上升。這不是對未來價格的預測；它是一個待油價、香港完成資料及就業數據驗證的分化市場假設。",
    researchPosition: "研究定位／8月31日收市 → 9月1日及本週驗證",
    usTitle: "美股：能源相對強勢、收益率仍高，選擇性AI參與未改變偏弱的日度廣度。",
    hkTitle: "港股：官方10:09 HKT快照走低；完成收市、成交及南向資料仍待核對。",
    crossTitle: "跨市場：確認的Larak行動、油價、日度收益率與公司價格反應必須按條件連結。",
    weekTitle: "本週關注：先核對香港完成資料與油價傳導，再看9月4日美國就業數據。",
    overviewCards: [["美股／8月31日完成收市", "Dow -0.70% · S&P -0.33% · Nasdaq -0.12%", "油價、地緣風險與較高日度收益率同時存在；不把它們寫成唯一因果。"], ["港股／9月1日10:09 HKT", "HSI -1.04% · HSCEI -0.80% · HSTECH -0.88%", "恒生指數公司官方、15分鐘受限更新；僅為盤中快照。"]],
    mode: { education: ["怎樣讀今天的報告", "先分開已完成美股收市、帶時間戳的港股盤中快照和未來日程；再測試能源、收益率與選擇性AI參與是否形成一致訊號。", ["國債日度平價收益率是官方每日參考，不是某一分鐘成交收益率。", "一個板塊ETF代理的日度回報不能代替所有成分股或市場整體廣度。", "9月1日香港快照受到15分鐘更新限制，不能替代收市、成交或南向資金資料。"]], analysis: ["當前論點與失效條件", "基本情景是地緣／油價風險與較高日度收益率令廣泛風險偏好承壓，而AI相對表現仍屬選擇性。論點需要油價、港股完成資料與9月4日就業數據共同檢驗。", ["若油價風險溢價回落且市場廣度改善，能源主導的防禦性可被削弱。", "若地緣或油價進一步升溫並伴隨長端壓力，分化可能加劇。", "就業數據必須與通脹、收益率與市場反應共同閱讀，不能預設單向結論。"]] },
    macro: [["VIX", "14.92", "Cboe 8月31日日度收市。"], ["2Y／10Y／30Y", "4.34%／4.75%／5.25%", "美國財政部8月31日日度平價收益率；非盤中成交報價。"], ["板塊代理廣度", "18.2% 一日正回報", "11個Select Sector SPDR ETF代理中僅Energy正回報；不是交易所A/D廣度。"], ["能源結算", "WTI $85.76／Brent $90.49", "AP／CNBC完成時段報道；不可據此推導持久油價路徑。"]],
    company: [["NVDA", "Reuters報道 +1.48%", "NVIDIA在8月31日完成時段相對上升，與三大指數普遍收低同時存在。", "這是選擇性AI參與，不足以單獨證明廣泛風險偏好或整條產業鏈同步改善。", "後續資料中心執行、供應與估值如何在非業績日被市場消化。"], ["能源", "XLE +2.04% 代理", "能源是11個板塊ETF代理的一日唯一正回報；AP與CNBC報道油價上升。", "相對強勢可與油價上升一致，但不能代替對供應中斷、航運或持久基本面的證明。", "可歸因的官方／可靠地緣進展、油價結算及更廣市場廣度。"], ["AMZN／加州公用事業", "AMZN -2.5%／PCG -20.1% 報道", "FTC與22州對Amazon的行動是指控，Amazon表示異議；AP報道PG&E受野火立法消息影響。", "法律及監管事件應保持公司特定性，不能機械延伸成科技或公用事業整體論點。", "程序性文件、公司回應與後續價格／基本面資訊。"]],
    hk: [["前一完成收市", "HSI 25,566.99（據報持平）", "CNBC的8月31日連續性報道；本證據包未取得精確HSCEI／HSTECH、成交或南向資料。"], ["今日盤中快照", "10:09 HKT · HSI -1.04% · HSTECH -0.88%", "恒生指數公司官方讀數；系統故障下僅有限15分鐘更新，並非收市。"], ["中國企業／生科", "HSCEI -0.80% · HSBIO -0.66%", "官方指數的盤中相對位置，不能歸因於單一政策、資金流或公司事件。"], ["收市後核對", "待官方資料", "核對完成指數、HKEX成交及Historical Daily Stock Connect；不估算南向。"]],
    cross: ["Reuters確認的Larak行動", "原油結算與能源相對表現", "美國日度平價收益率／估值邊界", "香港完成資料與勞工市場日程"],
    crossNarrative: "Reuters確認的是美軍於8月30日對Larak Island發射器的行動。油價及31日市場反應可觀察；但不確認霍爾木茲航道已恢復、商業航運正常化或衝突將導向單一價格路徑。",
    scenarios: [["正面", "有歸因的緩和消息配合較低油價和更廣板塊參與；香港完成資料不惡化。"], ["基準", "油價／地緣與收益率維持壓力，而NVIDIA等AI相對強勢仍屬選擇性。"], ["負面", "可核實的升級與更高油價／利率同時出現，廣度持續疲弱或香港收市走弱。"]],
    sourceNote: "本報告分開完成價格、官方日度利率／VIX、帶時間戳的香港盤中數據、官方日程及媒體已歸因報道。油輪水雷、完全停航、航運恢復比例、政策對話、加密與金屬數字及未核實個股／產業鏈說法沒有升格為結論。",
    crossKicker: "跨市場／條件式傳導", driverKicker: "傳導鏈／條件式", weekKicker: "本週／驗證日程", sourceKicker: "來源／審計軌跡", printKicker: "完整報告／列印版本"
  },
  CN: {
    edition: "BIT MARKET INTELLIGENCE · DAILY · 2026.09.01",
    asof: "as-of：2026年9月1日10:09 HKT · 美股完成时段为8月31日；港股为10:09 HKT盘中快照",
    nav: { overview: "总览", us: "美股", hk: "港股", cross: "跨市场", week: "本周关注", sources: "来源" },
    modes: { education: "投教阅读", analysis: "分析阅读" }, print: "导出完整PDF", printAction: "打印／保存PDF", completed: "完成交易时段", intraday: "盘中快照", fact: "事实", meaning: "市场含义", next: "下一验证", positive: "正面确认", negative: "负面确认", sourceTitle: "来源、权限与不确定性边界",
    title: "能源风险溢价与较高日度收益率压制大盘；AI仅呈现选择性相对强势。",
    thesis: "8月31日美股在油价上涨、地缘消息与较高美国国债日度平价收益率背景下小幅收低；Energy是11个板块ETF代理中唯一日涨板块。NVIDIA相对上涨属于选择性AI参与，不足以抵消仅18.2%的一日板块代理广度。下一步要分开核对油价／地缘、港股完成收市与9月4日就业数据。",
    summary: "研究摘要", summaryText: "可核实的是三大指数收低、VIX日度收市14.92、Brent结算于$90.49、10年期日度平价收益率4.75%，以及NVIDIA相对上涨。这不是对未来价格的预测；它是一个待油价、香港完成资料及就业数据验证的分化市场假设。",
    researchPosition: "研究定位／8月31日收市 → 9月1日及本周验证",
    usTitle: "美股：能源相对强势、收益率仍高，选择性AI参与未改变偏弱的日度广度。",
    hkTitle: "港股：官方10:09 HKT快照走低；完成收市、成交与南向数据仍待核对。",
    crossTitle: "跨市场：确认的Larak行动、油价、日度收益率与公司价格反应必须按条件连接。",
    weekTitle: "本周关注：先核对香港完成资料与油价传导，再看9月4日美国就业数据。",
    overviewCards: [["美股／8月31日完成收市", "Dow -0.70% · S&P -0.33% · Nasdaq -0.12%", "油价、地缘风险与较高日度收益率同时存在；不把它们写成唯一因果。"], ["港股／9月1日10:09 HKT", "HSI -1.04% · HSCEI -0.80% · HSTECH -0.88%", "恒生指数公司官方、15分钟受限更新；仅为盘中快照。"]],
    mode: { education: ["怎样读今天的报告", "先分开已完成美股收市、带时间戳的港股盘中快照和未来日程；再测试能源、收益率与选择性AI参与是否形成一致信号。", ["国债日度平价收益率是官方每日参考，不是某一分钟成交收益率。", "一个板块ETF代理的日度回报不能代替所有成分股或市场整体广度。", "9月1日香港快照受到15分钟更新限制，不能替代收市、成交或南向资金资料。"]], analysis: ["当前论点与失效条件", "基准情景是地缘／油价风险与较高日度收益率令广泛风险偏好承压，而AI相对表现仍属选择性。论点需要油价、港股完成资料与9月4日就业数据共同检验。", ["若油价风险溢价回落且市场广度改善，能源主导的防御性可被削弱。", "若地缘或油价进一步升温并伴随长端压力，分化可能加剧。", "就业数据必须与通胀、收益率与市场反应共同阅读，不能预设单向结论。"]] },
    macro: [["VIX", "14.92", "Cboe 8月31日日度收市。"], ["2Y／10Y／30Y", "4.34%／4.75%／5.25%", "美国财政部8月31日日度平价收益率；非盘中成交报价。"], ["板块代理广度", "18.2% 一日正回报", "11个Select Sector SPDR ETF代理中仅Energy正回报；不是交易所A/D广度。"], ["能源结算", "WTI $85.76／Brent $90.49", "AP／CNBC完成时段报道；不可据此推导持久油价路径。"]],
    company: [["NVDA", "Reuters报道 +1.48%", "NVIDIA在8月31日完成时段相对上涨，与三大指数普遍收低同时存在。", "这是选择性AI参与，不足以单独证明广泛风险偏好或整条产业链同步改善。", "后续数据中心执行、供应与估值如何在非业绩日被市场消化。"], ["能源", "XLE +2.04% 代理", "能源是11个板块ETF代理的一日唯一正回报；AP与CNBC报道油价上涨。", "相对强势可与油价上涨一致，但不能代替对供应中断、航运或持久基本面的证明。", "可归因的官方／可靠地缘进展、油价结算及更广市场广度。"], ["AMZN／加州公用事业", "AMZN -2.5%／PCG -20.1% 报道", "FTC与22州对Amazon的行动是指控，Amazon表示异议；AP报道PG&E受野火立法消息影响。", "法律及监管事件应保持公司特定性，不能机械延伸成科技或公用事业整体论点。", "程序性文件、公司回应与后续价格／基本面信息。"]],
    hk: [["前一完成收市", "HSI 25,566.99（据报持平）", "CNBC的8月31日连续性报道；本证据包未取得精确HSCEI／HSTECH、成交或南向资料。"], ["今日盘中快照", "10:09 HKT · HSI -1.04% · HSTECH -0.88%", "恒生指数公司官方读数；系统故障下仅有限15分钟更新，并非收市。"], ["中国企业／生科", "HSCEI -0.80% · HSBIO -0.66%", "官方指数的盘中相对位置，不能归因于单一政策、资金流或公司事件。"], ["收市后核对", "待官方资料", "核对完成指数、HKEX成交及Historical Daily Stock Connect；不估算南向。"]],
    cross: ["Reuters确认的Larak行动", "原油结算与能源相对表现", "美国日度平价收益率／估值边界", "香港完成资料与劳工市场日程"],
    crossNarrative: "Reuters确认的是美军于8月30日对Larak Island发射器的行动。油价及31日市场反应可观察；但不确认霍尔木兹航道已恢复、商业航运正常化或冲突将导向单一价格路径。",
    scenarios: [["正面", "有归因的缓和消息配合较低油价和更广板块参与；香港完成资料不恶化。"], ["基准", "油价／地缘与收益率维持压力，而NVIDIA等AI相对强势仍属选择性。"], ["负面", "可核实的升级与更高油价／利率同时出现，广度持续疲弱或香港收市走弱。"]],
    sourceNote: "本报告分开完成价格、官方日度利率／VIX、带时间戳的香港盘中数据、官方日程及媒体已归因报道。油轮水雷、完全停航、航运恢复比例、政策对话、加密与金属数字及未核实个股／产业链说法没有升级为结论。",
    crossKicker: "跨市场／条件式传导", driverKicker: "传导链／条件式", weekKicker: "本周／验证日程", sourceKicker: "来源／审计轨迹", printKicker: "完整报告／打印版本"
  },
  EN: {
    edition: "BIT MARKET INTELLIGENCE · DAILY · 2026.09.01",
    asof: "As of 1 Sep 2026 10:09 HKT · completed U.S. session: 31 Aug; Hong Kong: 10:09 HKT intraday snapshot",
    nav: { overview: "Overview", us: "U.S. Market", hk: "Hong Kong", cross: "Cross-market", week: "This Week", sources: "Sources" },
    modes: { education: "Education reading", analysis: "Analysis reading" }, print: "Export full PDF", printAction: "Print / Save PDF", completed: "Completed session", intraday: "Intraday snapshot", fact: "Fact", meaning: "What it means", next: "Next validation", positive: "Positive confirmation", negative: "Negative confirmation", sourceTitle: "Sources, entitlement and uncertainty boundary",
    title: "Energy risk premium and higher daily yields weighed on broad equities; AI showed only selective relative strength.",
    thesis: "The 31 Aug U.S. session closed modestly lower alongside higher oil, geopolitical headlines and elevated Treasury daily par yields; Energy was the sole positive ETF in the 11-sector proxy. NVIDIA’s relative gain is selective AI participation, not enough to offset 18.2% one-day sector-proxy breadth. The next tests are oil/geopolitics, Hong Kong’s completed close and the 4 September employment release—each read separately.",
    summary: "Research summary", summaryText: "Verified facts are lower broad indices, a 14.92 VIX daily close, Brent settlement at $90.49, a 4.75% 10Y daily par yield and NVIDIA’s relative gain. This is not a forecast: it is a split-market hypothesis to be tested against oil, Hong Kong completed data and employment evidence.",
    researchPosition: "RESEARCH POSITIONING / 31 AUG CLOSE → 1 SEP AND WEEKLY TESTS",
    usTitle: "U.S.: Energy strength and elevated yields persisted; selective AI participation did not change weak daily breadth.",
    hkTitle: "Hong Kong: the official 10:09 HKT snapshot is lower; completed close, turnover and southbound data still require verification.",
    crossTitle: "Cross-market: confirmed Larak action, oil, daily yields and company price reactions must connect conditionally.",
    weekTitle: "This week: validate Hong Kong completed data and oil transmission first, then the 4 September U.S. employment release.",
    overviewCards: [["U.S. / 31 Aug completed close", "Dow -0.70% · S&P -0.33% · Nasdaq -0.12%", "Oil, geopolitical risk and higher daily yields coexisted; none is claimed as the sole cause."], ["Hong Kong / 1 Sep 10:09 HKT", "HSI -1.04% · HSCEI -0.80% · HSTECH -0.88%", "Official Hang Seng Indexes limited 15-minute update; intraday snapshot only."]],
    mode: { education: ["How to read today’s report", "Separate the completed U.S. close, timestamped Hong Kong intraday snapshot and future schedule; then test whether energy, yields and selective AI participation form a consistent signal.", ["A Treasury daily par yield is an official daily reference, not a yield traded at one minute.", "One sector-ETF proxy’s daily return does not replace constituent-level or exchange advance–decline breadth.", "The 1 Sep Hong Kong snapshot has a 15-minute update limitation and cannot substitute for close, turnover or southbound flow."]], analysis: ["Current thesis and invalidation conditions", "The base case is that geopolitical/oil risk and elevated daily yields pressure broad risk appetite while AI relative strength remains selective. Oil, Hong Kong completed data and 4 September employment evidence must jointly test that thesis.", ["Lower oil risk premium with broader participation would weaken the energy-led defensive signal.", "Further attributable escalation alongside higher crude and long-end pressure would strengthen the split-market case.", "Employment data must be read alongside inflation, yields and market response; it does not imply a one-way conclusion."]] },
    macro: [["VIX", "14.92", "Cboe 31 Aug daily close."], ["2Y / 10Y / 30Y", "4.34% / 4.75% / 5.25%", "U.S. Treasury 31 Aug daily par yields; not intraday traded quotes."], ["Sector proxy breadth", "18.2% one-day positive", "Only Energy was positive in the 11 Select Sector SPDR ETF proxy; not exchange A/D breadth."], ["Energy settlements", "WTI $85.76 / Brent $90.49", "AP/CNBC completed-session reporting; no durable oil path is inferred."]],
    company: [["NVDA", "+1.48% reported", "NVIDIA rose relatively in the 31 Aug completed session while the three broad indices closed lower.", "This is selective AI participation, insufficient on its own to establish broad risk appetite or synchronized industry-chain improvement.", "How data-centre execution, supply and valuation are absorbed on non-earnings days."], ["Energy", "XLE +2.04% proxy", "Energy was the only positive one-day sector ETF proxy; AP and CNBC reported higher crude.", "Relative strength can align with higher oil but does not prove supply disruption, shipping conditions or durable fundamentals.", "Attributable official/reputable geopolitical developments, crude settlements and broader market breadth."], ["AMZN / California utilities", "AMZN -2.5% / PCG -20.1% reported", "The FTC and 22-state action against Amazon is an allegation which Amazon disputed; AP reported PG&E moved on wildfire-legislation reports.", "Legal and regulatory events remain company-specific; they should not mechanically become a technology or utilities-wide thesis.", "Procedural filings, company responses and subsequent price/fundamental evidence."]],
    hk: [["Prior completed close", "HSI 25,566.99 (reported flat)", "CNBC 31 Aug continuity coverage; exact HSCEI/HSTECH, turnover and southbound figures were not independently captured."], ["Today intraday snapshot", "10:09 HKT · HSI -1.04% · HSTECH -0.88%", "Official Hang Seng Indexes reading; a limited 15-minute update during the outage, not a close."], ["China enterprises / biotech", "HSCEI -0.80% · HSBIO -0.66%", "Official intraday index positions; no single-policy, flow or company causality is inferred."], ["Post-close check", "Official data pending", "Verify completed indices, HKEX turnover and Historical Daily Stock Connect; do not estimate southbound flow."]],
    cross: ["Reuters-confirmed Larak action", "Crude settlements and energy relative performance", "U.S. daily par yields / valuation boundary", "Hong Kong completed data and labour-market schedule"],
    crossNarrative: "Reuters confirmed the 30 Aug U.S. action against launchers on Larak Island. Oil and 31 Aug market reactions are observable; this does not verify an operating Hormuz corridor, normalized commercial shipping or a single durable price path from the conflict.",
    scenarios: [["Positive", "Attributable de-escalation arrives with lower oil and broader sector participation; Hong Kong completed data do not deteriorate."], ["Base", "Oil/geopolitical and yield pressure persists while relative strength in NVIDIA and other AI names remains selective."], ["Negative", "Verifiable escalation coincides with higher oil/rates, persistently weak breadth or a weaker Hong Kong close."]],
    sourceNote: "This report separates completed prices, official daily yields/VIX, timestamped Hong Kong intraday data, official schedules and attributable media reporting. Tanker mines, a complete shipping stoppage, traffic-restoration percentages, policy dialogue, crypto/metal figures and unverified stock or industry claims are not promoted to conclusions.",
    crossKicker: "CROSS-MARKET / CONDITIONAL READ-THROUGH", driverKicker: "DRIVER CHAIN / CONDITIONAL", weekKicker: "THIS WEEK / VERIFICATION AGENDA", sourceKicker: "SOURCES / AUDIT TRAIL", printKicker: "FULL REPORT / PRINT VERSION"
  }
};

export default function DailySep01Full({ printAll = false }: { printAll?: boolean }) {
  const query = new URLSearchParams(window.location.search);
  const [lang, setLang] = useState<Lang>(() => (["TW", "CN", "EN"].includes(query.get("lang") || "") ? query.get("lang") : "CN") as Lang);
  const [section, setSection] = useState<Section>(() => (["us", "hk", "cross", "week", "sources"].includes(query.get("market") || "") ? query.get("market") : "overview") as Section);
  const [mode, setMode] = useState<Mode>("analysis");
  const [windowSize, setWindowSize] = useState<"oneDay" | "fiveDay" | "twentyDay">("oneDay");
  const t = copy[lang];
  const go = (next: Section, nextLang = lang) => { const url = new URL(window.location.href); url.searchParams.set("date", "2026-09-01"); url.searchParams.set("market", next); url.searchParams.set("lang", nextLang); url.searchParams.delete("export"); window.history.replaceState({}, "", url); window.dispatchEvent(new Event("bit-location")); setSection(next); setLang(nextLang); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const exportPdf = () => { const url = new URL(window.location.href); url.searchParams.set("date", "2026-09-01"); url.searchParams.set("lang", lang); url.searchParams.set("export", "pdf"); url.searchParams.delete("market"); window.open(url.toString(), "_blank", "noopener,noreferrer"); };
  const Card = ({ title, value, body, onClick }: any) => <article onClick={onClick} className={`rounded-[12px] border border-[#E4E6EA] bg-white p-6 ${onClick ? "cursor-pointer transition hover:border-[#0040FF]" : ""}`}><p className="font-mono text-[10px] font-bold tracking-[.13em] text-[#0040FF]">{title}</p><p className="mt-5 font-mono text-xl font-semibold text-[#0A0D14]">{value}</p><p className="mt-4 text-sm leading-7 text-[#59657A]">{body}</p>{onClick && <p className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-[#0040FF]">{t.next}<ArrowRight size={14}/></p>}</article>;
  const Evidence = ({ item }: { item: string[] }) => <article className="rounded-[12px] border border-[#E4E6EA] bg-white p-6"><p className="font-display text-2xl">{item[0]} · {item[1]}</p><p className="mt-5 text-sm leading-7"><strong>{t.fact} · </strong>{item[2]}</p><p className="mt-4 text-sm leading-7 text-[#59657A]"><strong>{t.meaning} · </strong>{item[3]}</p><p className="mt-4 border-l-2 border-[#0040FF] pl-4 text-sm leading-7"><strong>{t.next} · </strong>{item[4]}</p></article>;
  const Hero = ({ kicker, title, body }: any) => <section className="mx-auto max-w-[1200px] px-5 py-12 sm:px-10 lg:px-[var(--layout-padding)]"><p className="section-kicker">{kicker}</p><h1 className="section-title mt-3 max-w-5xl">{title}</h1><p className="mt-5 max-w-4xl text-[16px] leading-8 text-[#59657A]">{body}</p></section>;
  const Overview = () => <main className="mx-auto max-w-[1200px] px-5 py-10 sm:px-10 lg:px-[var(--layout-padding)]"><section className="border-b border-[#E4E6EA] pb-10"><p className="section-kicker">{lang === "EN" ? "DAILY / COMPLETED U.S. CLOSE → TODAY" : lang === "TW" ? "每日／完成美股收市 → 今日" : "每日／完成美股收市 → 今日"}</p><h1 className="section-title mt-3 max-w-5xl">{t.title}</h1><p className="mt-6 max-w-4xl text-[17px] leading-8 text-[#59657A]">{t.thesis}</p><div className="mt-8 border-l-2 border-[#0040FF] bg-[#F5F7FA] p-5"><p className="font-mono text-[10px] font-bold tracking-[.14em] text-[#0040FF]">{t.summary.toUpperCase()}</p><p className="mt-3 max-w-4xl text-[15px] leading-7">{t.summaryText}</p></div></section><section className="grid gap-5 py-10 lg:grid-cols-2">{t.overviewCards.map((item: string[], i: number) => <Card key={item[0]} title={item[0]} value={item[1]} body={item[2]} onClick={printAll ? undefined : () => go(i === 0 ? "us" : "hk")}/>)}</section><section className="rounded-[12px] bg-[#0A0D14] p-7 text-white"><p className="font-mono text-[10px] tracking-[.16em] text-[#478DFF]">{t.researchPosition}</p><p className="mt-4 max-w-4xl text-[16px] leading-7 text-[#EDF1F7]">{t.mode[mode][1]}</p>{!printAll && <button onClick={() => go("week")} className="bit-action mt-6 inline-flex items-center gap-2 border border-[#478DFF] px-4 py-2 text-xs font-bold"><CalendarDays size={14}/>{t.nav.week}<ArrowRight size={14}/></button>}</section><section className="mt-10 rounded-[12px] border border-[#E4E6EA] bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="section-kicker">{lang === "EN" ? "READING MODE" : lang === "TW" ? "閱讀模式" : "阅读模式"}</p><h2 className="mt-3 font-display text-2xl">{t.mode[mode][0]}</h2></div>{!printAll && <div className="inline-flex rounded-[8px] border border-[#E4E6EA] p-1">{(["education", "analysis"] as Mode[]).map(item => <button key={item} onClick={() => setMode(item)} className={`bit-action px-3 py-2 text-xs font-bold ${mode === item ? "bg-[#0040FF] text-white" : "text-[#59657A]"}`}>{t.modes[item]}</button>)}</div>}</div><ul className="mt-5 grid gap-3 md:grid-cols-3">{t.mode[mode][2].map((item: string) => <li key={item} className="border-l-2 border-[#0040FF] pl-4 text-sm leading-7 text-[#59657A]">{item}</li>)}</ul></section></main>;
  const Heatmap = () => <section className="bg-[#0A0D14] px-5 py-12 text-white sm:px-10 lg:px-[var(--layout-padding)]"><div className="mx-auto max-w-[1200px]"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="font-mono text-[10px] tracking-[.16em] text-[#478DFF]">{lang === "EN" ? "SECTOR HEATMAP / COMPLETED 31 AUG" : lang === "TW" ? "板塊熱力圖／8月31日完成時段" : "板块热力图／8月31日完成时段"}</p><p className="mt-3 text-sm text-[#BFC7D6]">{lang === "EN" ? "Compare audited sector-proxy position across completed U.S. session windows." : lang === "TW" ? "比較不同完成美股時段窗口的經審計板塊代理位置。" : "比较不同完成美股时段窗口的经审计板块代理位置。"}</p></div><div className="flex gap-2">{(["oneDay", "fiveDay", "twentyDay"] as const).map(item => <button key={item} onClick={() => setWindowSize(item)} className={`bit-action border px-3 py-2 font-mono text-[10px] font-bold ${windowSize === item ? "border-[#478DFF] bg-[#0040FF] text-white" : "border-white/20 text-[#BFC7D6]"}`}>{item === "oneDay" ? "1D" : item === "fiveDay" ? "5D" : "20D"}</button>)}</div></div><div className="mt-6 grid gap-2 sm:grid-cols-3">{detail.sector_heatmap.map((item: any) => <div key={item.symbol} title={`1D ${pct(item.oneDay)} · 5D ${pct(item.fiveDay)} · 20D ${pct(item.twentyDay)}`} className="min-h-28 rounded-[8px] p-4 text-[#0A0D14]" style={{ background: heat(item[windowSize]) }}><p className="font-mono text-[10px] font-bold tracking-[.1em]">{item.symbol} · {sectorLabels[lang][item.label] || item.label}</p><p className="mt-4 font-mono text-2xl">{pct(item[windowSize])}</p></div>)}</div><p className="mt-5 text-xs text-[#B0B9C9]">{lang === "EN" ? "Green positive, grey neutral, orange-red negative." : lang === "TW" ? "綠色正向、灰色中性、橙紅負向。" : "绿色正向、灰色中性、橙红负向。"}</p></div></section>;
  const US = () => <main className="pb-12"><Hero kicker={lang === "EN" ? "U.S. MARKET / COMPLETED 31 AUG" : lang === "TW" ? "美股／8月31日完成時段" : "美股／8月31日完成时段"} title={t.usTitle} body={t.thesis}/><section className="bg-[#F5F7FA] px-5 py-8 sm:px-10 lg:px-[var(--layout-padding)]"><div className="mx-auto max-w-[1200px]"><p className="section-kicker">{t.completed}</p><div className="mt-5 grid border-l border-t border-[#E4E6EA] md:grid-cols-3">{Object.entries(us.index_close).map(([name, row]: any) => <article key={name} className="-ml-px -mt-px border border-[#E4E6EA] bg-white p-6"><p className="font-mono text-[10px] tracking-[.14em] text-[#59657A]">{name}</p><p className="mt-4 font-mono text-3xl font-semibold">{row.value.toLocaleString()}</p><p className={`mt-2 font-mono text-sm ${row.change_pct >= 0 ? "text-[#17733B]" : "text-[#C22F26]"}`}>{pct(row.change_pct)}</p></article>)}</div></div></section><section className="mx-auto max-w-[1200px] px-5 py-12 sm:px-10 lg:px-[var(--layout-padding)]"><p className="section-kicker">{lang === "EN" ? "MACRO / MARKET DRIVERS" : lang === "TW" ? "宏觀／市場驅動" : "宏观／市场驱动"}</p><div className="mt-6 grid border-l border-t border-[#E4E6EA] lg:grid-cols-4">{t.macro.map((item: string[]) => <article key={item[0]} className="-ml-px -mt-px border border-[#E4E6EA] bg-white p-6"><p className="font-mono text-[10px] tracking-[.12em] text-[#59657A]">{item[0]}</p><p className="mt-4 font-mono text-xl font-semibold">{item[1]}</p><p className="mt-4 text-sm leading-6 text-[#59657A]">{item[2]}</p></article>)}</div></section><section className="mx-auto max-w-[1200px] px-5 py-12 sm:px-10 lg:px-[var(--layout-padding)]"><p className="section-kicker">{lang === "EN" ? "STOCKS / INDUSTRY CHAIN" : lang === "TW" ? "個股／產業鏈" : "个股／产业链"}</p><div className="mt-6 grid gap-5 lg:grid-cols-3">{t.company.map((item: string[]) => <Evidence key={item[0]} item={item}/>)}</div></section><Heatmap/></main>;
  const HK = () => <main className="pb-12"><Hero kicker={lang === "EN" ? "HONG KONG / 1 SEP 10:09 HKT INTRADAY" : lang === "TW" ? "港股／9月1日10:09 HKT盤中" : "港股／9月1日10:09 HKT盘中"} title={t.hkTitle} body={lang === "EN" ? hk.intraday_snapshot.limitation : lang === "TW" ? "僅為盤中快照；不是完成收市、成交、南向資金或單一驅動結論。" : "仅为盘中快照；不是完成收市、成交、南向资金或单一驱动结论。"}/><section className="mx-auto max-w-[1200px] px-5 py-10 sm:px-10 lg:px-[var(--layout-padding)]"><div className="grid gap-5 lg:grid-cols-2">{t.hk.map((item: string[]) => <Card key={item[0]} title={item[0]} value={item[1]} body={item[2]}/>)}</div><section className="mt-10 rounded-[12px] border border-[#E4E6EA] bg-[#F5F7FA] p-6"><p className="section-kicker">{t.intraday}</p><div className="mt-5 grid border-l border-t border-[#E4E6EA] sm:grid-cols-2 lg:grid-cols-4">{Object.entries(hk.intraday_snapshot.indices).map(([name, row]: any) => <div key={name} className="-ml-px -mt-px border border-[#E4E6EA] bg-white p-5"><p className="font-mono text-[10px] font-bold tracking-[.12em] text-[#59657A]">{name}</p><p className="mt-3 font-mono text-2xl font-semibold">{row.value.toLocaleString()}</p><p className={`mt-2 font-mono text-xs ${row.change_pct >= 0 ? "text-[#17733B]" : "text-[#C22F26]"}`}>{pct(row.change_pct)}</p></div>)}</div></section></section></main>;
  const Cross = () => <main className="pb-12"><Hero kicker={t.crossKicker} title={t.crossTitle} body={t.crossNarrative}/><section className="mx-auto max-w-[1200px] px-5 py-8 sm:px-10 lg:px-[var(--layout-padding)]"><div className="rounded-[12px] bg-[#0A0D14] p-7 text-white"><p className="font-mono text-[10px] tracking-[.16em] text-[#478DFF]">{t.driverKicker}</p><div className="mt-7 grid border-l border-t border-white/15 md:grid-cols-4">{t.cross.map((item: string, index: number) => <div key={item} className="-ml-px -mt-px min-h-32 border border-white/15 p-5"><p className="font-mono text-[10px] text-[#478DFF]">0{index + 1}</p><p className="mt-4 text-sm leading-6">{item}</p></div>)}</div></div></section><section className="bg-[#F5F7FA] px-5 py-12 sm:px-10 lg:px-[var(--layout-padding)]"><div className="mx-auto grid max-w-[1200px] gap-5 lg:grid-cols-3">{t.scenarios.map((item: string[], index: number) => <article key={item[0]} className={`rounded-[12px] border p-6 ${index === 0 ? "border-[#10B99A]" : index === 2 ? "border-[#F9584A]" : "border-[#E4E6EA]"}`}><p className="font-display text-2xl">{item[0]}</p><p className="mt-5 text-sm leading-7 text-[#59657A]">{item[1]}</p></article>)}</div></section></main>;
  const Week = () => <main className="pb-12"><Hero kicker={t.weekKicker} title={t.weekTitle} body={lang === "EN" ? "Official schedules and future conditions remain separated from results. Each row defines what can support or weaken the current thesis." : lang === "TW" ? "官方日程與未來條件均與結果分開。每列界定甚麼會支持或削弱當前論點。" : "官方日程与未来条件均与结果分开。每列界定什么会支持或削弱当前论点。"}/><section className="bg-[#F5F7FA] px-5 py-10 sm:px-10 lg:px-[var(--layout-padding)]"><div className="mx-auto max-w-[1200px] space-y-4">{thesis.this_week.map((item: any, index: number) => <article key={item.id} className="grid gap-5 rounded-[12px] border border-[#E4E6EA] bg-white p-6 lg:grid-cols-[.8fr_1.4fr_1fr_1fr]"><div><p className="font-mono text-[10px] font-bold tracking-[.14em] text-[#0040FF]">0{index + 1}</p><p className="mt-4 font-display text-2xl">{item.event}</p><p className="mt-3 flex items-center gap-2 font-mono text-xs text-[#59657A]"><CalendarDays size={14}/>{item.when}</p></div><p className="text-sm leading-7 text-[#59657A]">{item.boundary}</p><p className="border-l-2 border-[#10B99A] pl-4 text-sm leading-6 text-[#17733B]"><CheckCircle2 className="mr-2 inline" size={15}/><strong>{t.positive} · </strong>{item.positive}</p><p className="border-l-2 border-[#F9584A] pl-4 text-sm leading-6 text-[#C22F26]"><CircleAlert className="mr-2 inline" size={15}/><strong>{t.negative} · </strong>{item.negative}</p></article>)}</div></section></main>;
  const Sources = () => <main className="mx-auto max-w-[1200px] px-5 py-10 sm:px-10 lg:px-[var(--layout-padding)]"><p className="section-kicker">{t.sourceKicker}</p><h1 className="section-title mt-3">{t.sourceTitle}</h1><p className="mt-5 max-w-4xl text-[16px] leading-7 text-[#59657A]">{t.sourceNote}</p><div className="mt-8 space-y-3">{sources.map(item => printAll ? <div key={item.id} className="flex items-center justify-between gap-4 rounded-[12px] border border-[#E4E6EA] bg-white p-5"><div><p className="font-mono text-[10px] font-bold tracking-[.14em] text-[#0040FF]">[{item.id}] {item.market.toUpperCase()} · {item.tier}</p><p className="mt-2 text-sm text-[#0A0D14]">{item.label[lang]}</p></div></div> : <a key={item.id} href={item.url} target="_blank" rel="noreferrer" className="group flex items-center justify-between gap-4 rounded-[12px] border border-[#E4E6EA] bg-white p-5 transition hover:border-[#0040FF]"><div><p className="font-mono text-[10px] font-bold tracking-[.14em] text-[#0040FF]">[{item.id}] {item.market.toUpperCase()} · {item.tier}</p><p className="mt-2 text-sm text-[#0A0D14]">{item.label[lang]}</p></div><ExternalLink className="shrink-0 text-[#59657A] group-hover:text-[#0040FF]" size={18}/></a>)}</div><p className="mt-10 border-t border-[#E4E6EA] pt-6 text-xs leading-6 text-[#59657A]">{lang === "EN" ? "AI-assisted content, based on the sources shown, for BIT internal market monitoring and research discussion. It is not approved client communication or promotional material. It is not personalised investment advice, a securities recommendation, a buy/sell/short instruction or a guarantee of return." : lang === "TW" ? "本內容由人工智能輔助整理，按所示來源供BIT內部市場監測與研究討論使用；不是經批准的客戶通訊或推廣材料。內容不構成個人化投資建議、證券推薦、買賣或沽空指令，亦不保證投資回報。" : "本内容由人工智能辅助整理，按所示来源供BIT内部市场监测与研究讨论使用；不是经批准的客户沟通或推广材料。内容不构成个人化投资建议、证券推荐、买卖或沽空指令，也不保证投资回报。"}</p></main>;
  const content = section === "overview" ? <Overview/> : section === "us" ? <US/> : section === "hk" ? <HK/> : section === "cross" ? <Cross/> : section === "week" ? <Week/> : <Sources/>;
  const all = <><PrintSection title={t.nav.overview}><Overview/></PrintSection><PrintSection title={t.nav.us}><US/></PrintSection><PrintSection title={t.nav.hk}><HK/></PrintSection><PrintSection title={t.nav.cross}><Cross/></PrintSection><PrintSection title={t.nav.week}><Week/></PrintSection><PrintSection title={t.nav.sources}><Sources/></PrintSection></>;
  if (printAll) return <div className="bit-v3 bit-print-document min-h-screen bg-white text-[#0A0D14]"><div className="mx-auto max-w-[1200px] px-5 py-8 sm:px-10"><p className="font-mono text-[10px] font-bold tracking-[.16em] text-[#0040FF]">{t.edition}</p><p className="mt-3 text-sm text-[#59657A]">{t.asof}</p><button onClick={() => window.print()} className="bit-action bit-print-action mt-6 inline-flex items-center gap-2 border border-[#0040FF] px-4 py-2 text-xs font-bold text-[#0040FF]"><Printer size={15}/>{t.printAction}</button></div>{all}</div>;
  return <div className="bit-v3 bit-page min-h-screen bg-white text-[#0A0D14]"><header className="bit-reference-header sticky top-0 z-30 bg-white"><div className="bit-header-main mx-auto flex max-w-[1400px] items-start justify-between gap-3 px-5 py-4 sm:items-center sm:gap-6 sm:px-10 lg:px-[var(--layout-padding)]"><div className="flex min-w-0 items-start gap-3 sm:items-center sm:gap-8"><div className="flex shrink-0 items-center gap-2" aria-label="BIT"><img src={`${base}brand/BIT-Logo-blue.svg`} alt="" className="h-8 w-8 rounded-[8px] object-contain"/><img src={`${base}brand/BIT-Logo-black.svg`} alt="BIT" className="bit-wordmark-crop"/></div><div className="hidden h-14 w-px shrink-0 bg-[#DDD5C8] sm:block"/><div className="min-w-0"><p className="font-mono text-[9px] font-medium tracking-[.13em] text-[#5B6473] sm:text-[13px]">{t.edition}</p><p className="mt-2 text-[10px] font-medium leading-4 text-[#5B6473] sm:text-[17px] sm:leading-5">{lang === "EN" ? "1 Sep 10:09 HKT · U.S. 31 Aug close · HK 10:09 intraday" : lang === "TW" ? "1 Sep 10:09 HKT · 美股31 Aug收市 · 港股10:09盤中" : "1 Sep 10:09 HKT · 美股31 Aug收市 · 港股10:09盘中"}</p></div></div><div className="bit-header-controls flex shrink-0 flex-col items-end gap-2 sm:flex-row sm:items-center"><div className="inline-flex rounded-[8px] border border-[#E4E6EA] bg-white p-1">{(["TW", "CN", "EN"] as Lang[]).map(item => <button key={item} onClick={() => go(section, item)} className={`bit-action min-h-0 px-2 py-1.5 font-mono text-[10px] font-bold sm:px-2.5 ${lang === item ? "bg-[#0040FF] text-white" : "text-[#59657A]"}`}>{item}</button>)}</div><button onClick={exportPdf} className="bit-action inline-flex items-center gap-1.5 border border-[#0040FF] px-2.5 py-2 font-mono text-[9px] font-bold text-[#0040FF] sm:px-3 sm:text-[10px]"><Printer size={13}/>{t.print}</button></div></div><div className="bit-header-nav mx-auto flex max-w-[1400px] gap-6 overflow-x-auto px-5 sm:gap-10 sm:px-10 lg:px-[var(--layout-padding)]">{(Object.keys(t.nav) as Section[]).map(item => <button key={item} onClick={() => go(item)} className={`bit-action whitespace-nowrap border-b-[3px] px-0 pb-4 pt-3 text-[16px] font-medium ${section === item ? "border-[#0040FF] text-[#0040FF]" : "text-[#59657A]"}`}>{t.nav[item]}</button>)}</div></header>{content}</div>;
}

function PrintSection({ title, children }: { title: string; children: any }) { return <section className="bit-print-section border-t border-[#E4E6EA]"><div className="mx-auto max-w-[1200px] px-5 py-4 sm:px-10"><p className="font-mono text-[10px] font-bold tracking-[.16em] text-[#0040FF]">{title.toUpperCase()}</p></div>{children}</section>; }
