/**
 * BIT Market Intelligence — 26 Aug 2026 daily edition.
 * Evidence boundary: 25 Aug U.S. completed session; 26 Aug 10:42 HKT Hong Kong intraday only.
 */
import { ArrowRight, CalendarDays, CheckCircle2, CircleAlert, ExternalLink, Printer } from "lucide-react";
import { useState } from "react";
import usData from "../../../data/2026-08-26/us_market.json";
import hkData from "../../../data/2026-08-26/hk_market.json";
import thesisData from "../../../data/2026-08-26/thesis.json";
import sourceData from "../../../data/2026-08-26/sources.json";
import detailData from "../../../data/2026-08-26/market_analytics_detail.json";

type Lang = "TW" | "CN" | "EN";
type Section = "overview" | "us" | "hk" | "cross" | "week" | "sources";
type Mode = "education" | "analysis";
const us: any = usData, hk: any = hkData, thesis: any = thesisData, detail: any = detailData;
const sources: any[] = (sourceData as any).sources;
const base = import.meta.env.BASE_URL;
const pct = (n: number) => `${n > 0 ? "+" : ""}${n.toFixed(2)}%`;
const heat = (n: number) => n > .1 ? "#10B99A" : n < -.1 ? "#FF6A1A" : "#E5E7EB";

const copy: Record<Lang, any> = {
  TW: {
    edition: "BIT MARKET INTELLIGENCE · DAILY · 2026.08.26", asof: "as-of：2026年8月26日10:43 HKT · 美股完成時段為8月25日；港股為10:42 HKT盤中快照", nav: { overview: "總覽", us: "美股", hk: "港股", cross: "跨市場", week: "本週關注", sources: "來源" }, modes: { education: "投教閱讀", analysis: "分析閱讀" }, print: "導出完整PDF", printAction: "列印／儲存PDF", completed: "完成交易時段", intraday: "盤中快照", fact: "事實", meaning: "市場含義", next: "下一驗證", positive: "正面確認", negative: "負面確認", sourceTitle: "來源、權限與不確定性邊界",
    title: "半導體反彈與較低收益率提供估值喘息；可持續性仍交給BEA、NVIDIA與港股完成收市驗證。", thesis: "8月25日美股三大指數上升，科技及半導體反彈與較低日度美債平價收益率同時出現；但這只能說明事件前風險偏好修復，不能替代今日宏觀數據與NVIDIA業績對AI需求、估值與資本開支的實質檢驗。", summary: "研究摘要", summaryText: "市場的可觀察變化是風險波動下降、科技反彈與10年期日度平價收益率降至4.64%。下一步不是把一天反彈寫成趨勢反轉，而是核對BEA數據、NVIDIA指引與港股收市是否提供一致確認。",
    usTitle: "美股：完成時段反彈，但AI敘事仍等待業績與宏觀結果。", hkTitle: "港股：官方10:42 HKT指數快照普遍走高，仍不是完成收市。", crossTitle: "跨市場：利率、航運風險與關稅只在可觀察價格／公司證據出現時才構成傳導。", weekTitle: "本週關注：已排期事件與結果嚴格分開。",
    overviewCards: [["美股／8月25日完成收市", "Dow +0.30% · S&P +0.32% · Nasdaq +0.66%", "科技反彈與較低收益率共存；不是已證實的單一因果。"], ["港股／8月26日10:42 HKT", "HSI +0.95% · HSTECH +1.64%", "官方15分鐘受限更新；僅作盤中快照。"]],
    mode: { education: ["怎樣讀今天的報告", "先分開完成收市、盤中快照和未來日程，再把市場敘事視為可驗證假設。", ["美國財政部日度平價收益率不是某一分鐘的即時成交收益率。", "港股上升只有在收市、成交和公司／板塊證據跟上後才可升格為結論。", "NVIDIA業績在本報告時點仍未公布，不能用預期代替結果。"]], analysis: ["當前論點與失效條件", "基準情景是風險偏好在重要事件前修復。只有宏觀結果、NVIDIA指引與跨市場價格訊號一致，才能把修復升格為更持久的論點。", ["BEA數據若降低長端風險溢價，支持估值修復。", "NVIDIA資料中心／前瞻訊號必須支持AI基建需求。", "港股科技相對強度需要完成收市與成交／南向資料確認。"]] },
    macro: [["VIX", "15.45", "Cboe日度收市，較8月24日15.85下降。"], ["2Y／10Y／30Y", "3.89%／4.64%／5.17%", "財政部日度平價收益率；不是盤中報價。"], ["SOX", "約+1.4%", "Reuters報道的指數級反彈；不補寫未核實點位。"], ["催化劑邊界", "結果待定", "BEA與NVIDIA結果均在HKT截稿後／待公布。"]],
    company: [["NVDA", "Reuters報道 +2.2%", "Reuters報道的財報前反彈及七日跌勢結束；不代表結果已知。", "這反映事件前定位有修復，不能替代財報基本面。", "資料中心需求、交付節奏與指引。"], ["半導體", "SOX 約+1.4%", "可報告的是板塊反彈，而非把所有個股變動歸因於同一消息。", "指數反彈本身不足以證明記憶體、光通訊或設計鏈基本面同步改善。", "業績後把指數反彈與個別公司基本面分開。"], ["NVDA／AMD", "官方產品公告", "Jetson Orin Nano 2及AMD UCIe為路線圖證據，不是同日股價的充分原因。", "產品公告可補充技術路線資訊，但不應代替收入、採用或定價證據。", "未來供應時間、客戶採用與可量化訂單。"]],
    hk: [["昨日完成收市", "HSI -0.02% · HSTECH -0.12% · HSCEI -0.31%", "8月25日Tier 2完成市場資料；總成交HK$254.079bn。"], ["今日盤中快照", "10:42 HKT · HSI +0.95% · HSTECH +1.64%", "官方指數公司系統故障下的有限15分鐘更新；不能替代收市。"], ["相對位置", "HSBIO +2.11%", "生物科技在快照中領先；只是指數相對表現，不是單一政策或資金流因果。"], ["收市後核對", "待官方資料", "核對完成指數、成交及HKEX Historical Daily；南向不以估計值填補。"]],
    cross: ["美國日度收益率／估值", "半導體與AI風險偏好", "香港科技／中國企業相對表現", "收市與公司披露驗證"],
    scenarios: [["正面", "BEA結果支持較低長端風險溢價、NVIDIA指引支持需求，港股完成收市保留科技相對強度。"], ["基準", "事件前反彈但宏觀、業績與港股流量尚未形成一致確認。"], ["負面", "通脹／收益率壓力、NVIDIA指引不足或港股盤中強勢未能在收市確認。"]],
    sourceNote: "本報告將完成價格、有時間戳的盤中資料、官方日程與未確認產業／外部材料分開。油價精確結算、DRAM 401%及加密數字未取得完整可審計來源，因此沒有升格為定論。", disclosure: "本內容由人工智能輔助整理，按所示來源供BIT內部市場監測與研究討論使用；不是經批准的客戶通訊或推廣材料。內容不構成個人化投資建議、證券推薦、買賣或沽空指令，亦不保證投資回報。"
  },
  CN: {
    edition: "BIT MARKET INTELLIGENCE · DAILY · 2026.08.26", asof: "as-of：2026年8月26日10:43 HKT · 美股完成时段为8月25日；港股为10:42 HKT盘中快照", nav: { overview: "总览", us: "美股", hk: "港股", cross: "跨市场", week: "本周关注", sources: "来源" }, modes: { education: "投教阅读", analysis: "分析阅读" }, print: "导出完整PDF", printAction: "打印／保存PDF", completed: "完成交易时段", intraday: "盘中快照", fact: "事实", meaning: "市场含义", next: "下一验证", positive: "正面确认", negative: "负面确认", sourceTitle: "来源、权限与不确定性边界",
    title: "半导体反弹与较低收益率提供估值喘息；可持续性仍交给BEA、NVIDIA与港股完成收市验证。", thesis: "8月25日美股三大指数上涨，科技及半导体反弹与较低日度美债平价收益率同时出现；但这只能说明事件前风险偏好修复，不能替代今日宏观数据与NVIDIA业绩对AI需求、估值与资本开支的实质检验。", summary: "研究摘要", summaryText: "市场的可观察变化是风险波动下降、科技反弹与10年期日度平价收益率降至4.64%。下一步不是把一天反弹写成趋势反转，而是核对BEA数据、NVIDIA指引与港股收市是否提供一致确认。",
    usTitle: "美股：完成时段反弹，但AI叙事仍等待业绩与宏观结果。", hkTitle: "港股：官方10:42 HKT指数快照普遍走高，仍不是完成收市。", crossTitle: "跨市场：利率、航运风险与关税只在可观察价格／公司证据出现时才构成传导。", weekTitle: "本周关注：已排期事件与结果严格分开。",
    overviewCards: [["美股／8月25日完成收市", "Dow +0.30% · S&P +0.32% · Nasdaq +0.66%", "科技反弹与较低收益率共存；不是已证实的单一因果。"], ["港股／8月26日10:42 HKT", "HSI +0.95% · HSTECH +1.64%", "官方15分钟受限更新；仅作盘中快照。"]],
    mode: { education: ["怎样读今天的报告", "先分开完成收市、盘中快照和未来日程，再把市场叙事视为可验证假设。", ["美国财政部日度平价收益率不是某一分钟的即时成交收益率。", "港股上涨只有在收市、成交和公司／板块证据跟上后才可升格为结论。", "NVIDIA业绩在本报告时点仍未公布，不能用预期代替结果。"]], analysis: ["当前论点与失效条件", "基准情景是风险偏好在重要事件前修复。只有宏观结果、NVIDIA指引与跨市场价格信号一致，才能把修复升格为更持久的论点。", ["BEA数据若降低长端风险溢价，支持估值修复。", "NVIDIA数据中心／前瞻信号必须支持AI基建需求。", "港股科技相对强度需要完成收市与成交／南向数据确认。"]] },
    macro: [["VIX", "15.45", "Cboe日度收市，较8月24日15.85下降。"], ["2Y／10Y／30Y", "3.89%／4.64%／5.17%", "财政部日度平价收益率；不是盘中报价。"], ["SOX", "约+1.4%", "Reuters报道的指数级反弹；不补写未核实点位。"], ["催化剂边界", "结果待定", "BEA与NVIDIA结果均在HKT截稿后／待公布。"]],
    company: [["NVDA", "Reuters报道 +2.2%", "Reuters报道的财报前反弹及七日跌势结束；不代表结果已知。", "这反映事件前定位有修复，不能替代财报基本面。", "数据中心需求、交付节奏与指引。"], ["半导体", "SOX 约+1.4%", "可报告的是板块反弹，而非把所有个股变动归因于同一消息。", "指数反弹本身不足以证明存储、光通信或设计链基本面同步改善。", "业绩后把指数反弹与个别公司基本面分开。"], ["NVDA／AMD", "官方产品公告", "Jetson Orin Nano 2及AMD UCIe为路线图证据，不是同日股价的充分原因。", "产品公告可补充技术路线信息，但不应代替收入、采用或定价证据。", "未来供应时间、客户采用与可量化订单。"]],
    hk: [["昨日完成收市", "HSI -0.02% · HSTECH -0.12% · HSCEI -0.31%", "8月25日Tier 2完成市场资料；总成交HK$254.079bn。"], ["今日盘中快照", "10:42 HKT · HSI +0.95% · HSTECH +1.64%", "官方指数公司系统故障下的有限15分钟更新；不能替代收市。"], ["相对位置", "HSBIO +2.11%", "生物科技在快照中领先；只是指数相对表现，不是单一政策或资金流因果。"], ["收市后核对", "待官方资料", "核对完成指数、成交及HKEX Historical Daily；南向不以估计值填补。"]],
    cross: ["美国日度收益率／估值", "半导体与AI风险偏好", "香港科技／中国企业相对表现", "收市与公司披露验证"], scenarios: [["正面", "BEA结果支持较低长端风险溢价、NVIDIA指引支持需求，港股完成收市保留科技相对强度。"], ["基准", "事件前反弹但宏观、业绩与港股流量尚未形成一致确认。"], ["负面", "通胀／收益率压力、NVIDIA指引不足或港股盘中强势未能在收市确认。"]],
    sourceNote: "本报告将完成价格、有时间戳的盘中资料、官方日程与未确认产业／外部材料分开。油价精确结算、DRAM 401%及加密数字未取得完整可审计来源，因此没有升级为定论。", disclosure: "本内容由人工智能辅助整理，按所示来源供BIT内部市场监测与研究讨论使用；不是经批准的客户沟通或推广材料。内容不构成个人化投资建议、证券推荐、买卖或沽空指令，也不保证投资回报。"
  },
  EN: {
    edition: "BIT MARKET INTELLIGENCE · DAILY · 2026.08.26", asof: "As of 26 Aug 2026 10:43 HKT · completed U.S. session: 25 Aug; Hong Kong: 10:42 HKT intraday snapshot", nav: { overview: "Overview", us: "U.S. Market", hk: "Hong Kong", cross: "Cross-market", week: "This Week", sources: "Sources" }, modes: { education: "Education reading", analysis: "Analysis reading" }, print: "Export full PDF", printAction: "Print / Save PDF", completed: "Completed session", intraday: "Intraday snapshot", fact: "Fact", meaning: "What it means", next: "Next validation", positive: "Positive confirmation", negative: "Negative confirmation", sourceTitle: "Sources, entitlement and uncertainty boundary",
    title: "Semiconductor rebound and lower yields offer a valuation reprieve; durability now belongs to BEA, NVIDIA and the Hong Kong close.", thesis: "The 25 Aug U.S. session rose as technology and semiconductors rebounded alongside lower daily Treasury par yields. That is evidence of pre-event risk appetite repair, not a substitute for the macro and NVIDIA tests that must establish AI demand, valuation and capex durability.", summary: "Research summary", summaryText: "Observable changes were lower volatility, technology rebound and a 4.64% 10Y daily par yield. The next step is not to call one up-day a trend reversal; it is to test whether BEA, NVIDIA guidance and the Hong Kong close confirm the same direction.",
    usTitle: "U.S.: completed-session rebound, but the AI narrative still awaits earnings and macro evidence.", hkTitle: "Hong Kong: official 10:42 HKT index snapshot is broadly higher, but remains not a completed close.", crossTitle: "Cross-market: rates, shipping risk and tariffs transmit only when observable price or company evidence appears.", weekTitle: "This week: scheduled events and outcomes remain strictly separated.",
    overviewCards: [["U.S. / 25 Aug completed close", "Dow +0.30% · S&P +0.32% · Nasdaq +0.66%", "Technology rebound and lower yields coexisted; neither is proven as a sole cause."], ["Hong Kong / 26 Aug 10:42 HKT", "HSI +0.95% · HSTECH +1.64%", "Official limited 15-minute updates; intraday snapshot only."]],
    mode: { education: ["How to read today’s report", "Separate completed closes, intraday snapshots and scheduled events before treating a market narrative as a testable hypothesis.", ["A daily Treasury par yield is not a real-time traded yield at one minute.", "Hong Kong strength becomes a conclusion only after the close, turnover and company/sector evidence agree.", "NVIDIA earnings were not yet released at this report cutoff; expectation cannot replace outcome."]], analysis: ["Current thesis and invalidation conditions", "The base case is pre-event risk appetite repair. It upgrades only when macro results, NVIDIA guidance and cross-market price evidence agree.", ["BEA evidence that lowers long-end risk premium supports the valuation repair.", "NVIDIA data-centre and forward signals must support AI-infrastructure demand.", "Hong Kong technology relative strength needs completed close, turnover and southbound confirmation."]] },
    macro: [["VIX", "15.45", "Cboe daily close, down from 15.85 on 24 Aug."], ["2Y / 10Y / 30Y", "3.89% / 4.64% / 5.17%", "Treasury daily par yields; not intraday quotes."], ["SOX", "about +1.4%", "Reuters-reported index rebound; no unsupported close level is added."], ["Catalyst boundary", "results pending", "BEA and NVIDIA results remain after / pending at this HKT cutoff."]],
    company: [["NVDA", "+2.2% reported", "Reuters-reported pre-earnings rebound and end to a seven-session decline; it does not reveal results.", "This shows pre-event positioning repair, not the earnings fundamentals themselves.", "Data-centre demand, delivery cadence and guidance."], ["Semiconductors", "SOX about +1.4%", "The reportable fact is a sector rebound—not a single explanation for every component move.", "An index rebound does not establish simultaneous improvement across memory, optical or design-chain fundamentals.", "Separate index rebound from company fundamentals after results."], ["NVDA / AMD", "Official product notices", "Jetson Orin Nano 2 and AMD UCIe are roadmap evidence, not sufficient same-day price causality.", "Product notices add technology-roadmap context but do not replace revenue, adoption or pricing evidence.", "Future availability, adoption and measurable orders."]],
    hk: [["Prior completed close", "HSI -0.02% · HSTECH -0.12% · HSCEI -0.31%", "25 Aug Tier 2 completed-market data; turnover HK$254.079bn."], ["Today intraday snapshot", "10:42 HKT · HSI +0.95% · HSTECH +1.64%", "Limited 15-minute update during provider outage; not a close."], ["Relative position", "HSBIO +2.11%", "Biotech leads the snapshot; that is index relative performance, not single-policy or flow causality."], ["Post-close check", "Official data pending", "Verify completed indices, turnover and HKEX Historical Daily; do not estimate southbound flow."]],
    cross: ["U.S. daily yields / valuation", "Semiconductor and AI risk appetite", "Hong Kong technology / China-enterprise relative performance", "Close and company-disclosure validation"], scenarios: [["Positive", "BEA supports lower long-end risk premium, NVIDIA guidance supports demand, and Hong Kong close retains technology relative strength."], ["Base", "Pre-event rebound occurs without aligned macro, earnings and Hong Kong-flow confirmation."], ["Negative", "Inflation/yield pressure, insufficient NVIDIA guidance or intraday Hong Kong strength fails to confirm at the close."]],
    sourceNote: "This report separates completed prices, timestamped intraday data, official schedules and unconfirmed industry/external material. Precise oil settlements, the DRAM 401% claim and crypto figures were not promoted because complete auditable sources were unavailable.", disclosure: "AI-assisted content, based on the sources shown, for BIT internal market monitoring and research discussion. It is not approved client communication or promotional material. It is not personalised investment advice, a securities recommendation, a buy/sell/short instruction or a guarantee of return."
  }
};

const sectorLabels: Record<Lang, Record<string, string>> = {
  EN: {}, TW: { Technology: "科技", "Communication Services": "通訊服務", "Health Care": "醫療保健", Utilities: "公用事業", Financials: "金融", "Real Estate": "房地產", Materials: "原材料", "Consumer Discretionary": "非必需消費", Industrials: "工業", "Consumer Staples": "必需消費", Energy: "能源" }, CN: { Technology: "科技", "Communication Services": "通信服务", "Health Care": "医疗保健", Utilities: "公用事业", Financials: "金融", "Real Estate": "房地产", Materials: "原材料", "Consumer Discretionary": "非必需消费", Industrials: "工业", "Consumer Staples": "必需消费", Energy: "能源" }
};

export default function DailyAug26Full({ printAll = false }: { printAll?: boolean }) {
  const query = new URLSearchParams(window.location.search);
  const [lang, setLang] = useState<Lang>(() => (["TW", "CN", "EN"].includes(query.get("lang") || "") ? query.get("lang") : "CN") as Lang);
  const [section, setSection] = useState<Section>(() => (["us", "hk", "cross", "week", "sources"].includes(query.get("market") || "") ? query.get("market") : "overview") as Section);
  const [mode, setMode] = useState<Mode>("analysis");
  const [windowSize, setWindowSize] = useState<"oneDay" | "fiveDay" | "twentyDay">("oneDay");
  const t = copy[lang];
  const go = (next: Section, nextLang = lang) => { const u = new URL(window.location.href); u.searchParams.set("date", "2026-08-26"); u.searchParams.set("market", next); u.searchParams.set("lang", nextLang); u.searchParams.delete("export"); window.history.replaceState({}, "", u); window.dispatchEvent(new Event("bit-location")); setSection(next); setLang(nextLang); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const exportPdf = () => { const u = new URL(window.location.href); u.searchParams.set("date", "2026-08-26"); u.searchParams.set("lang", lang); u.searchParams.set("export", "pdf"); u.searchParams.delete("market"); window.open(u.toString(), "_blank", "noopener,noreferrer"); };
  const Hero = ({ kicker, title, body }: any) => <section className="mx-auto max-w-[1200px] px-5 py-12 sm:px-10 lg:px-[var(--layout-padding)]"><p className="section-kicker">{kicker}</p><h1 className="section-title mt-3 max-w-5xl">{title}</h1><p className="mt-5 max-w-4xl text-[16px] leading-8 text-[#59657A]">{body}</p></section>;
  const Card = ({ title, value, body, onClick }: any) => <article onClick={onClick} className={`rounded-[12px] border border-[#E4E6EA] bg-white p-6 ${onClick ? "cursor-pointer transition hover:border-[#0040FF]" : ""}`}><p className="font-mono text-[10px] font-bold tracking-[.13em] text-[#0040FF]">{title}</p><p className="mt-5 font-mono text-xl font-semibold text-[#0A0D14]">{value}</p><p className="mt-4 text-sm leading-7 text-[#59657A]">{body}</p>{onClick && <p className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-[#0040FF]">{t.next}<ArrowRight size={14}/></p>}</article>;
  const Evidence = ({ title, fact, meaning, next, badge }: any) => <article className="rounded-[12px] border border-[#E4E6EA] bg-white p-6">{badge && <span className="rounded-full bg-[#E8F0FF] px-2 py-1 font-mono text-[9px] font-bold text-[#0040FF]">{badge}</span>}<p className="mt-4 font-display text-2xl">{title}</p><p className="mt-5 text-sm leading-7 text-[#0A0D14]"><strong>{t.fact} · </strong>{fact}</p><p className="mt-4 text-sm leading-7 text-[#59657A]"><strong>{t.meaning} · </strong>{meaning}</p><p className="mt-4 border-l-2 border-[#0040FF] pl-4 text-sm leading-7 text-[#0A0D14]"><strong>{t.next} · </strong>{next}</p></article>;
  const Overview = () => <main className="mx-auto max-w-[1200px] px-5 py-10 sm:px-10 lg:px-[var(--layout-padding)]"><section className="border-b border-[#E4E6EA] pb-10"><p className="section-kicker">DAILY / COMPLETED U.S. CLOSE → TODAY</p><h1 className="section-title mt-3 max-w-5xl">{t.title}</h1><p className="mt-6 max-w-4xl text-[17px] leading-8 text-[#59657A]">{t.thesis}</p><div className="mt-8 border-l-2 border-[#0040FF] bg-[#F5F7FA] p-5"><p className="font-mono text-[10px] font-bold tracking-[.14em] text-[#0040FF]">{t.summary.toUpperCase()}</p><p className="mt-3 max-w-4xl text-[15px] leading-7">{t.summaryText}</p></div></section><section className="grid gap-5 py-10 lg:grid-cols-2">{t.overviewCards.map((x: string[], i: number) => <Card key={x[0]} title={x[0]} value={x[1]} body={x[2]} onClick={printAll ? undefined : () => go(i === 0 ? "us" : "hk")}/>)}</section><section className="rounded-[12px] bg-[#0A0D14] p-7 text-white"><p className="font-mono text-[10px] tracking-[.16em] text-[#478DFF]">RESEARCH POSITIONING / 25 AUG CLOSE → 26 AUG TESTS</p><p className="mt-4 max-w-4xl text-[16px] leading-7 text-[#EDF1F7]">{t.mode[mode][1]}</p>{!printAll && <button onClick={() => go("week")} className="bit-action mt-6 inline-flex items-center gap-2 border border-[#478DFF] px-4 py-2 text-xs font-bold"><CalendarDays size={14}/>{t.nav.week}<ArrowRight size={14}/></button>}</section><section className="mt-10 rounded-[12px] border border-[#E4E6EA] bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="section-kicker">READING MODE</p><h2 className="mt-3 font-display text-2xl">{t.mode[mode][0]}</h2></div>{!printAll && <div className="inline-flex rounded-[8px] border border-[#E4E6EA] p-1">{(["education", "analysis"] as Mode[]).map(m => <button key={m} onClick={() => setMode(m)} className={`bit-action px-3 py-2 text-xs font-bold ${mode === m ? "bg-[#0040FF] text-white" : "text-[#59657A]"}`}>{t.modes[m]}</button>)}</div>}</div><ul className="mt-5 grid gap-3 md:grid-cols-3">{t.mode[mode][2].map((x: string) => <li key={x} className="border-l-2 border-[#0040FF] pl-4 text-sm leading-7 text-[#59657A]">{x}</li>)}</ul></section></main>;
  const Heatmap = () => <section className="bg-[#0A0D14] px-5 py-12 text-white sm:px-10 lg:px-[var(--layout-padding)]"><div className="mx-auto max-w-[1200px]"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="font-mono text-[10px] tracking-[.16em] text-[#478DFF]">{lang === "EN" ? "SECTOR HEATMAP / COMPLETED 25 AUG" : lang === "TW" ? "板塊熱力圖／8月25日完成時段" : "板块热力图／8月25日完成时段"}</p><p className="mt-3 text-sm text-[#BFC7D6]">{lang === "EN" ? "Compare audited sector-proxy position across completed U.S. session windows." : lang === "TW" ? "比較不同完成美股時段窗口的經審計板塊代理位置。" : "比较不同完成美股时段窗口的经审计板块代理位置。"}</p></div><div className="flex flex-wrap gap-2">{(["oneDay", "fiveDay", "twentyDay"] as const).map(k => <button key={k} onClick={() => setWindowSize(k)} className={`bit-action border px-3 py-2 font-mono text-[10px] font-bold ${windowSize === k ? "border-[#478DFF] bg-[#0040FF] text-white" : "border-white/20 text-[#BFC7D6]"}`}>{k === "oneDay" ? "1D" : k === "fiveDay" ? "5D" : "20D"}</button>)}</div></div><div className="mt-6 grid gap-2 sm:grid-cols-3">{detail.sector_heatmap.map((x: any) => <div key={x.symbol} title={`1D ${pct(x.oneDay)} · 5D ${pct(x.fiveDay)} · 20D ${pct(x.twentyDay)}`} className="min-h-28 rounded-[8px] p-4 text-[#0A0D14]" style={{ background: heat(x[windowSize]) }}><p className="font-mono text-[10px] font-bold tracking-[.1em]">{x.symbol} · {sectorLabels[lang][x.label] || x.label}</p><p className="mt-4 font-mono text-2xl">{pct(x[windowSize])}</p></div>)}</div><p className="mt-5 text-xs text-[#B0B9C9]">{lang === "EN" ? "Green positive, grey neutral, orange-red negative." : lang === "TW" ? "綠色正向、灰色中性、橙紅負向。" : "绿色正向、灰色中性、橙红负向。"}</p></div></section>;
  const US = () => <main className="pb-12"><Hero kicker={lang === "EN" ? "U.S. MARKET / COMPLETED 25 AUG" : lang === "TW" ? "美股／8月25日完成時段" : "美股／8月25日完成时段"} title={t.usTitle} body={t.thesis}/><section className="bg-[#F5F7FA] px-5 py-8 sm:px-10 lg:px-[var(--layout-padding)]"><div className="mx-auto max-w-[1200px]"><p className="section-kicker">{t.completed}</p><div className="mt-5 grid border-l border-t border-[#E4E6EA] md:grid-cols-3">{Object.entries(us.index_close).map(([name, row]: any) => <article key={name} className="-ml-px -mt-px border border-[#E4E6EA] bg-white p-6"><p className="font-mono text-[10px] tracking-[.14em] text-[#59657A]">{name}</p><p className="mt-4 font-mono text-3xl font-semibold">{row.value.toLocaleString()}</p><p className="mt-2 font-mono text-sm text-[#17733B]">{pct(row.change_pct)}</p></article>)}</div></div></section><section className="mx-auto max-w-[1200px] px-5 py-12 sm:px-10 lg:px-[var(--layout-padding)]"><p className="section-kicker">{lang === "EN" ? "MACRO / MARKET DRIVERS" : lang === "TW" ? "宏觀／市場驅動" : "宏观／市场驱动"}</p><div className="mt-6 grid border-l border-t border-[#E4E6EA] lg:grid-cols-4">{t.macro.map((x: string[]) => <article key={x[0]} className="-ml-px -mt-px border border-[#E4E6EA] bg-white p-6"><p className="font-mono text-[10px] tracking-[.12em] text-[#59657A]">{x[0]}</p><p className="mt-4 font-mono text-xl font-semibold">{x[1]}</p><p className="mt-4 text-sm leading-6 text-[#59657A]">{x[2]}</p></article>)}</div></section><section className="mx-auto max-w-[1200px] px-5 py-12 sm:px-10 lg:px-[var(--layout-padding)]"><p className="section-kicker">{lang === "EN" ? "STOCKS / INDUSTRY CHAIN" : lang === "TW" ? "個股／產業鏈" : "个股／产业链"}</p><div className="mt-6 grid gap-5 lg:grid-cols-3">{t.company.map((x: string[]) => <Evidence key={x[0]} title={`${x[0]} · ${x[1]}`} fact={x[2]} meaning={x[3]} next={x[4]} />)}</div></section><Heatmap/></main>;
  const HK = () => <main className="pb-12"><Hero kicker={lang === "EN" ? "HONG KONG / 26 AUG 10:42 HKT INTRADAY" : lang === "TW" ? "港股／8月26日10:42 HKT盤中" : "港股／8月26日10:42 HKT盘中"} title={t.hkTitle} body={lang === "EN" ? hk.intraday_snapshot.limitation : lang === "TW" ? "僅為盤中快照；不是完成收市、成交、南向資金或單一驅動結論。" : "仅为盘中快照；不是完成收市、成交、南向资金或单一驱动结论。"}/><section className="mx-auto max-w-[1200px] px-5 py-10 sm:px-10 lg:px-[var(--layout-padding)]"><div className="grid gap-5 lg:grid-cols-2">{t.hk.map((x: string[], i: number) => <Card key={x[0]} title={x[0]} value={x[1]} body={x[2]}/>)}</div><section className="mt-10 rounded-[12px] border border-[#E4E6EA] bg-[#F5F7FA] p-6"><p className="section-kicker">{t.intraday}</p><div className="mt-5 grid border-l border-t border-[#E4E6EA] sm:grid-cols-2 lg:grid-cols-4">{Object.entries(hk.intraday_snapshot.indices).map(([name, row]: any) => <div key={name} className="-ml-px -mt-px border border-[#E4E6EA] bg-white p-5"><p className="font-mono text-[10px] font-bold tracking-[.12em] text-[#59657A]">{name}</p><p className="mt-3 font-mono text-2xl font-semibold">{row.value.toLocaleString()}</p><p className="mt-2 font-mono text-xs text-[#17733B]">{pct(row.change_pct)}</p></div>)}</div></section></section></main>;
  const Cross = () => <main className="pb-12"><Hero kicker={lang === "EN" ? "CROSS-MARKET / CONDITIONAL READ-THROUGH" : lang === "TW" ? "跨市場／條件式傳導" : "跨市场／条件式传导"} title={t.crossTitle} body={lang === "EN" ? "The framework follows observable transmission rather than treating one geopolitical or policy headline as a deterministic asset call." : lang === "TW" ? "框架追蹤可觀察傳導，而非把單一地緣或政策標題寫成資產的決定性結論。" : "框架追踪可观察传导，而非把单一地缘或政策标题写成资产的决定性结论。"}/><section className="mx-auto max-w-[1200px] px-5 py-8 sm:px-10 lg:px-[var(--layout-padding)]"><div className="rounded-[12px] bg-[#0A0D14] p-7 text-white"><p className="font-mono text-[10px] tracking-[.16em] text-[#478DFF]">{lang === "EN" ? "DRIVER CHAIN / CONDITIONAL" : lang === "TW" ? "傳導鏈／條件式" : "传导链／条件式"}</p><div className="mt-7 grid border-l border-t border-white/15 md:grid-cols-4">{t.cross.map((x: string, i: number) => <div key={x} className="-ml-px -mt-px min-h-32 border border-white/15 p-5"><p className="font-mono text-[10px] text-[#478DFF]">0{i + 1}</p><p className="mt-4 text-sm leading-6">{x}</p></div>)}</div><p className="mt-6 text-sm leading-7 text-[#BFC7D6]">{lang === "EN" ? "Oman confirmed consultations and a proposed phased navigation framework. It does not confirm an operating corridor, normal shipping or a permanent agreement; precise oil settlements were not inserted without readable official settlement data." : lang === "TW" ? "阿曼確認磋商及提議的分階段航行框架。這不確認航道已運作、商業航運已正常或永久協議已達成；未取得可讀官方結算資料時，不插入精確油價。" : "阿曼确认磋商及提议的分阶段航行框架。这不确认航道已运作、商业航运已正常或永久协议已达成；未取得可读官方结算资料时，不插入精确油价。"}</p></div></section><section className="bg-[#F5F7FA] px-5 py-12 sm:px-10 lg:px-[var(--layout-padding)]"><div className="mx-auto grid max-w-[1200px] gap-5 lg:grid-cols-3">{t.scenarios.map((x: string[], i: number) => <article key={x[0]} className={`rounded-[12px] border p-6 ${i === 0 ? "border-[#10B99A]" : i === 2 ? "border-[#F9584A]" : "border-[#E4E6EA]"}`}><p className="font-display text-2xl">{x[0]}</p><p className="mt-5 text-sm leading-7 text-[#59657A]">{x[1]}</p></article>)}</div></section></main>;
  const Week = () => <main className="pb-12"><Hero kicker={lang === "EN" ? "THIS WEEK / VERIFICATION AGENDA" : lang === "TW" ? "本週／驗證日程" : "本周／验证日程"} title={t.weekTitle} body={lang === "EN" ? "Official schedules are separated from results. Each row defines what would support or weaken the current thesis." : lang === "TW" ? "官方日程與結果分開。每一列均界定甚麼會支持或削弱當前論點。" : "官方日程与结果分开。每一列均界定什么会支持或削弱当前论点。"}/><section className="bg-[#F5F7FA] px-5 py-10 sm:px-10 lg:px-[var(--layout-padding)]"><div className="mx-auto max-w-[1200px] space-y-4">{thesis.this_week.map((r: any, i: number) => <article key={r.id} className="grid gap-5 rounded-[12px] border border-[#E4E6EA] bg-white p-6 lg:grid-cols-[.8fr_1.4fr_1fr_1fr]"><div><p className="font-mono text-[10px] font-bold tracking-[.14em] text-[#0040FF]">0{i + 1}</p><p className="mt-4 font-display text-2xl">{r.event}</p><p className="mt-3 flex items-center gap-2 font-mono text-xs text-[#59657A]"><CalendarDays size={14}/>{r.when}</p></div><p className="text-sm leading-7 text-[#59657A]">{r.boundary}</p><p className="border-l-2 border-[#10B99A] pl-4 text-sm leading-6 text-[#17733B]"><CheckCircle2 className="mr-2 inline" size={15}/><strong>{t.positive} · </strong>{r.positive}</p><p className="border-l-2 border-[#F9584A] pl-4 text-sm leading-6 text-[#C22F26]"><CircleAlert className="mr-2 inline" size={15}/><strong>{t.negative} · </strong>{r.negative}</p></article>)}</div></section></main>;
  const Sources = () => <main className="mx-auto max-w-[1200px] px-5 py-10 sm:px-10 lg:px-[var(--layout-padding)]"><p className="section-kicker">{lang === "EN" ? "SOURCES / AUDIT TRAIL" : lang === "TW" ? "來源／審計軌跡" : "来源／审计轨迹"}</p><h1 className="section-title mt-3">{t.sourceTitle}</h1><p className="mt-5 max-w-4xl text-[16px] leading-7 text-[#59657A]">{t.sourceNote}</p><div className="mt-8 space-y-3">{sources.map(s => printAll ? <div key={s.id} className="flex items-center justify-between gap-4 rounded-[12px] border border-[#E4E6EA] bg-white p-5"><div><p className="font-mono text-[10px] font-bold tracking-[.14em] text-[#0040FF]">[{s.id}] {s.market.toUpperCase()} · {s.tier}</p><p className="mt-2 text-sm text-[#0A0D14]">{s.label[lang]}</p></div></div> : <a key={s.id} href={s.url} target="_blank" rel="noreferrer" className="group flex items-center justify-between gap-4 rounded-[12px] border border-[#E4E6EA] bg-white p-5 transition hover:border-[#0040FF]"><div><p className="font-mono text-[10px] font-bold tracking-[.14em] text-[#0040FF]">[{s.id}] {s.market.toUpperCase()} · {s.tier}</p><p className="mt-2 text-sm text-[#0A0D14]">{s.label[lang]}</p></div><ExternalLink className="shrink-0 text-[#59657A] group-hover:text-[#0040FF]" size={18}/></a>)}</div><p className="mt-10 border-t border-[#E4E6EA] pt-6 text-xs leading-6 text-[#59657A]">{t.disclosure}</p></main>;
  const content = section === "overview" ? <Overview/> : section === "us" ? <US/> : section === "hk" ? <HK/> : section === "cross" ? <Cross/> : section === "week" ? <Week/> : <Sources/>;
  const all = <><PrintSection title={t.nav.overview}><Overview/></PrintSection><PrintSection title={t.nav.us}><US/></PrintSection><PrintSection title={t.nav.hk}><HK/></PrintSection><PrintSection title={t.nav.cross}><Cross/></PrintSection><PrintSection title={t.nav.week}><Week/></PrintSection><PrintSection title={t.nav.sources}><Sources/></PrintSection></>;
  if (printAll) return <div className="bit-v3 bit-print-document min-h-screen bg-white text-[#0A0D14]"><div className="mx-auto max-w-[1200px] px-5 py-8 sm:px-10"><p className="font-mono text-[10px] font-bold tracking-[.16em] text-[#0040FF]">{t.edition}</p><p className="mt-3 text-sm text-[#59657A]">{t.asof}</p><button onClick={() => window.print()} className="bit-action bit-print-action mt-6 inline-flex items-center gap-2 border border-[#0040FF] px-4 py-2 text-xs font-bold text-[#0040FF]"><Printer size={15}/>{t.printAction}</button></div>{all}</div>;
  return <div className="bit-v3 bit-page min-h-screen bg-white text-[#0A0D14]"><header className="bit-reference-header sticky top-0 z-30 bg-white"><div className="bit-header-main mx-auto flex max-w-[1400px] items-start justify-between gap-3 px-5 py-4 sm:items-center sm:gap-6 sm:px-10 lg:px-[var(--layout-padding)]"><div className="flex min-w-0 items-start gap-3 sm:items-center sm:gap-8"><div className="flex shrink-0 items-center gap-2" aria-label="BIT"><img src={`${base}brand/BIT-Logo-blue.svg`} alt="" className="h-8 w-8 rounded-[8px] object-contain"/><img src={`${base}brand/BIT-Logo-black.svg`} alt="BIT" className="bit-wordmark-crop"/></div><div className="hidden h-14 w-px shrink-0 bg-[#DDD5C8] sm:block"/><div className="min-w-0"><p className="font-mono text-[9px] font-medium tracking-[.13em] text-[#5B6473] sm:text-[13px]">{t.edition}</p><p className="mt-2 text-[10px] font-medium leading-4 text-[#5B6473] sm:text-[17px] sm:leading-5">{lang === "EN" ? "As of 26 Aug 10:43 HKT · U.S. 25 Aug close · HK 10:42 intraday" : lang === "TW" ? "26 Aug 10:43 HKT · 美股25 Aug收市 · 港股10:42盤中" : "26 Aug 10:43 HKT · 美股25 Aug收市 · 港股10:42盘中"}</p></div></div><div className="bit-header-controls flex shrink-0 flex-col items-end gap-2 sm:flex-row sm:items-center"><div className="inline-flex rounded-[8px] border border-[#E4E6EA] bg-white p-1">{(["TW", "CN", "EN"] as Lang[]).map(l => <button key={l} onClick={() => go(section, l)} className={`bit-action min-h-0 px-2 py-1.5 font-mono text-[10px] font-bold sm:px-2.5 ${lang === l ? "bg-[#0040FF] text-white" : "text-[#59657A]"}`}>{l}</button>)}</div><button onClick={exportPdf} className="bit-action inline-flex items-center gap-1.5 border border-[#0040FF] px-2.5 py-2 font-mono text-[9px] font-bold text-[#0040FF] sm:px-3 sm:text-[10px]"><Printer size={13}/>{t.print}</button></div></div><div className="bit-header-nav mx-auto flex max-w-[1400px] gap-6 overflow-x-auto px-5 sm:gap-10 sm:px-10 lg:px-[var(--layout-padding)]">{(Object.keys(t.nav) as Section[]).map(k => <button key={k} onClick={() => go(k)} className={`bit-action whitespace-nowrap border-b-[3px] px-0 pb-4 pt-3 text-[16px] font-medium ${section === k ? "border-[#0040FF] text-[#0040FF]" : "border-transparent text-[#59657A]"}`}>{t.nav[k]}</button>)}</div></header>{content}</div>;
}

function PrintSection({ title, children }: { title: string; children: any }) { return <section className="bit-print-section border-t border-[#E4E6EA]"><div className="mx-auto max-w-[1200px] px-5 py-4 sm:px-10"><p className="font-mono text-[10px] font-bold tracking-[.16em] text-[#0040FF]">{title.toUpperCase()}</p></div>{children}</section>; }
